// Isolated regression fixture: explicitly acknowledge the notice before exercising the app.
import {saveUsageConsent} from '/usage-consent.mjs';saveUsageConsent(localStorage);
import * as pdfjs from '/vendor/pdfjs/build/pdf.mjs';
import {extractPdfParagraphs,migratePdfLayout} from '/pdf-layout.mjs';
import {bindPdfTextLayer,pdfBlockSpans} from '/pdf-text.mjs';
import {highlightSource,findSourceBlock} from '/highlight.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/build/pdf.worker.mjs';
const out=document.getElementById('results');let passed=0,failed=0;const assert=(v,msg)=>{if(!v)throw Error(msg);};
async function test(name,fn){try{await fn();passed++;out.textContent+=`PASS ${name}\n`;}catch(e){failed++;out.textContent+=`FAIL ${name}: ${e.message}\n`;}}
const bytes=await(await fetch('/fixture.pdf')).arrayBuffer(),pdf=await pdfjs.getDocument({data:bytes.slice(0),standardFontDataUrl:'/vendor/pdfjs/standard_fonts/'}).promise;
const all=[],content=[];for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),c=await p.getTextContent({includeMarkedContent:true});content.push(c);all.push(...extractPdfParagraphs(c,p.getViewport({scale:1}),n,await p.getStructTree()));}
await test('Actual PDF produces four single-column paragraphs instead of a combined chunk',()=>{const blocks=all.filter(b=>b.page===1&&!b.heading&&!b.artifact);assert(blocks.length===4,'got '+blocks.length);for(let i=0;i<4;i++)assert(blocks[i].text.startsWith('Paragraph '+['ONE','TWO','THREE','FOUR'][i]),'incorrect boundary');});
await test('Actual two-column PDF produces six separate paragraphs in reading order',()=>{const blocks=all.filter(b=>b.page===2&&!b.heading&&!b.artifact);assert(blocks.length===6,'got '+blocks.length);assert(blocks.slice(0,3).every(b=>b.text.startsWith('LEFT')),'left reading order');assert(blocks.slice(3).every(b=>b.text.startsWith('RIGHT')),'right reading order');});
const p=await pdf.getPage(1),viewport=p.getViewport({scale:1}),page=document.createElement('div');page.className='pdf-page';page.dataset.page='1';page.style.cssText=`position:relative;width:${viewport.width}px;height:${viewport.height}px;--scale-factor:1;--total-scale-factor:1`;const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;page.append(canvas);document.getElementById('page').append(page);await p.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const layer=document.createElement('div');layer.className='textLayer';page.append(layer);const textLayer=new pdfjs.TextLayer({textContentSource:content[0],container:layer,viewport});await textLayer.render();const blocks=all.filter(b=>b.page===1);bindPdfTextLayer(textLayer,blocks);
await test('Source highlighter uses exact PDF text-item membership and never the neighbouring paragraph',()=>{const target=blocks.find(b=>b.text.startsWith('Paragraph THREE')),next=blocks.find(b=>b.text.startsWith('Paragraph FOUR'));assert(highlightSource(target,{scroll:false}),'no highlight');const targetSpans=pdfBlockSpans(page,target),nextSpans=pdfBlockSpans(page,next);assert(targetSpans.length>1,'missing target lines');assert(targetSpans.every(s=>!nextSpans.includes(s)),'overlap');const bounds=[...page.querySelectorAll('.source-highlight')].map(e=>e.getBoundingClientRect()),nextTop=Math.min(...nextSpans.map(s=>s.getBoundingClientRect().top));assert(bounds.length===targetSpans.length,'incorrect mark count');assert(bounds.every(b=>b.bottom<nextTop),'cross-paragraph highlight');});
await test('Legacy PDF evidence remains resolvable after migration, without misassigning new IDs',()=>{const legacy={id:'legacy',blocks:[{id:'p1b1',page:1,text:blocks.filter(b=>!b.heading).map(b=>b.text).join(' ')}],cards:[{blockId:'p1b1',page:1,title:'Old merged note',explanation:'This was produced from multiple paragraphs.'}],summary:'Previous [p1b1]',history:[]};const migrated=migratePdfLayout(legacy,{blocks:all,pages:2,outline:[]});assert(findSourceBlock(migrated,{id:'p1b1'}).legacy,'old ID silently reassigned');assert(migrated.archivedCards.length===1&&migrated.cards.length===0,'old note not preserved separately');});
out.textContent+=`\n${passed} passed, ${failed} failed`;document.title=`PDF tests: ${passed} passed, ${failed} failed`;
const seed=document.createElement('button');seed.textContent='打开旧版 PDF 迁移测试';seed.onclick=async()=>{const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('paper-space',1);req.onupgradeneeded=()=>req.result.createObjectStore('documents',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const body=blocks.filter(b=>!b.heading&&!b.artifact);const combined={...body[0],id:'p1b1',text:body.map(b=>b.text).join(' '),bottom:body.at(-1).bottom,height:body.at(-1).bottom-body[0].y};delete combined.lines;delete combined.itemIndices;const doc={id:'v06-legacy',name:'0.6-PDF段落测试.pdf',type:'pdf',bytes,blocks:[combined,...all.filter(b=>b.page===2)],pages:2,outline:[],history:[],code:[],lastPage:1,cards:[{blockId:'p1b1',page:1,title:'旧版跨段旁注',category:'测试',explanation:'旧版把数据来源、架构和外部测试合在一起。'}],summary:'历史导读 [p1b1]'};await new Promise((resolve,reject)=>{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(doc);tx.oncomplete=resolve;tx.onerror=reject;});localStorage.setItem('paper-space-active-doc',doc.id);location.href='/';};document.body.append(seed);
