import {createDesktopUI} from '/desktop-ui.mjs';
import {readWordHTML,matchWordSource} from '/word-import.mjs';
import {renderMarkdown} from '/rich-text.mjs';
import {createLibrary} from '/library.mjs';
const out=document.getElementById('results');let passed=0,failed=0;
const assert=(value,message)=>{if(!value)throw Error(message);};
async function test(name,fn){try{await fn();passed++;
out.textContent+=`PASS ${name}\n`;}catch(e){failed++;out.textContent+=`FAIL ${name}: ${e.message}\n`;}}
const bytes=await (await fetch('/fixture.docx')).arrayBuffer();
const result=await mammoth.convertToHtml({arrayBuffer:bytes},{externalFileAccess:false});
const parsed=readWordHTML(result.value);
await test('Embedded Word image and caption survive actual DOCX conversion',()=>{assert(parsed.figures.length===1,'figure missing');assert(parsed.figures[0].src.startsWith('data:image/png;base64,'),'image data missing');assert(parsed.blocks.some(b=>b.text.startsWith('Fig. 1.')),'caption missing');assert(parsed.figures[0].afterId==='w2','image ordering changed');});
await test('Legacy text IDs and pages remain identical, wrong Word is rejected',()=>{const p=new DOMParser().parseFromString(result.value,'text/html');const blocks=[...p.body.querySelectorAll('h1,h2,h3,p,li,table')].filter(e=>!e.parentElement?.closest('table,li')).map(e=>({text:e.textContent.trim()})).filter(b=>b.text);assert(matchWordSource({blocks},parsed),'legacy mismatch');assert(!matchWordSource({blocks:[{text:'different paper'}]},parsed),'wrong source accepted');assert(parsed.blocks.every((b,i)=>b.id===`w${i+1}`&&b.page===1),'IDs changed');});
await test('Unsupported and remote images do not disappear silently or load externally',()=>{const p=readWordHTML('<p>Caption<img src="https://example.com/a.png"><img src="data:image/x-emf;base64,QUFB"></p>');assert(p.figures.length===2&&p.figures.every(f=>!f.src&&f.unsupported),'untrusted image admitted');});
await test('Citation runs deduplicate IDs while preserving distinct same-page sources',()=>{const host=document.createElement('div');const sources=[{id:'w1',page:1,text:'First evidence'},{id:'w2',page:1,text:'Second evidence'},{id:'w3',page:15,text:'Third evidence'}];let selected;renderMarkdown(host,'**Claim** [w1] [w1] [w2] [w3]',{materials:sources,onCitation:s=>selected=s});assert(host.querySelectorAll('.citation-group').length===1,'not folded');assert(host.querySelector('.citation-sources').hidden,'expanded by default');assert(host.querySelectorAll('.citation-source').length===3,'lost/doubled evidence');host.querySelector('.citation-group > button').click();assert(!host.querySelector('.citation-sources').hidden,'cannot expand');host.querySelectorAll('.citation-source button')[1].click();assert(selected.id==='w2','wrong source targeted');});
await test('Unknown citations and HTML stay visible/inert',()=>{const host=document.createElement('div');renderMarkdown(host,'Claim [w1] [unknown]\n\n<script>alert(1)</script>',{materials:[{id:'w1',page:1,text:'Evidence'}]});assert(host.textContent.includes('unknown'),'unknown source hidden');assert(!host.querySelector('script'),'unsafe HTML');});
const ids=['documentList','docCount','trashBtn','codeBtn','exportBtn','overviewBtn','explainBtn','newChatBtn','prevPage','nextPage','pageInput','sendBtn','docTitle','outline','readingContent','readerStatus','pageTotal','deleteName','confirmDelete','trashList','toast','clearTrash','purgeName','confirmPurge'];
for(const id of ids){const el=document.createElement(id.includes('Btn')||['confirmDelete','confirmPurge','clearTrash'].includes(id)?'button':'div');el.id=id;document.getElementById('fixture').append(el);}for(const id of ['deleteDialog','trashDialog','purgeDialog']){const el=document.createElement('dialog');el.id=id;document.body.append(el);}
const state={docs:[{id:'only',name:'Test only',type:'docx',pages:1,history:[{text:'kept'}],cards:[{title:'kept'}]}],busy:false,excluded:new Set()};state.doc=state.docs[0];let saved,failSave=false,purged=[],failPurge=false;
const $=id=>document.getElementById(id),node=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;},button=(text,fn,cls)=>{const e=node('button',cls,text);e.onclick=fn;return e;};
let lib;lib=createLibrary({state,$,node,button,purgeDocs:async docs=>{if(failPurge)return false;purged=docs.map(d=>d.id);return true;},saveDoc:async d=>{if(failSave)return false;saved=structuredClone(d);return true;},activate:async d=>{state.doc=d;lib.list();},readerTools:{reset(){}},toast:text=>{$('toast').textContent=text;},refresh(){}});
await test('Deletion waits for confirmation, last-document empty state, and undo preserves notes',async()=>{lib.list();$('documentList').querySelector('.document-delete').click();assert(!state.doc.deletedAt,'deleted before confirmation');await $('confirmDelete').onclick();assert(saved.deletedAt&&state.doc===null,'last deletion failed');assert($('codeBtn').disabled,'empty actions enabled');assert($('documentList').children.length===0,'deleted item visible');assert(saved.history[0].text==='kept'&&saved.cards[0].title==='kept','notes lost');await $('toast').querySelector('button').onclick();assert(!state.doc.deletedAt&&state.doc.history.length===1,'undo lost notes');});
await test('Storage failure leaves the document intact',async()=>{failSave=true;$('documentList').querySelector('.document-delete').click();await $('confirmDelete').onclick();assert(!state.doc.deletedAt&&state.doc.id==='only','failed write mutated library');$('deleteDialog').close();failSave=false;});
await test('Recycle bin restores a saved deletion after library reload',async()=>{$('documentList').querySelector('.document-delete').click();await $('confirmDelete').onclick();state.docs=[structuredClone(saved)];lib.list();$('trashBtn').click();assert($('trashList').textContent.includes('Test only'),'persisted deletion missing');await $('trashList').querySelector('button').onclick();assert(state.doc.id==='only'&&!state.doc.deletedAt,'restore failed');});

await test('Permanent removal requires separate confirmation and cancellation preserves records',async()=>{state.docs=[{id:'trash-a',name:'Discarded',type:'txt',pages:1,deletedAt:1},{id:'live',name:'Live',type:'txt',pages:1}];state.doc=state.docs[1];lib.list();$('trashBtn').click();$('trashList').querySelectorAll('button')[1].click();assert($('purgeDialog').open,'missing confirmation');assert(!purged.length&&state.docs.length===2,'deleted before confirmation');$('purgeDialog').close();});
await test('Failed permanent removal preserves recoverable record',async()=>{failPurge=true;$('trashBtn').click();$('trashList').querySelectorAll('button')[1].click();await $('confirmPurge').onclick();assert(state.docs.some(d=>d.id==='trash-a'),'record lost on failure');$('purgeDialog').close();failPurge=false;});
await test('Confirmed removal deletes only target recycle-bin record',async()=>{$('trashBtn').click();$('trashList').querySelectorAll('button')[1].click();await $('confirmPurge').onclick();assert(purged.join(',')==='trash-a','wrong purge target');assert(state.docs.length===1&&state.docs[0].id==='live','live document removed');assert($('clearTrash').disabled,'empty trash still enabled');$('trashDialog').close();});
await test('Bulk purge includes only recycle bin and stops during model work',async()=>{state.docs.push({id:'trash-b',name:'B',deletedAt:1},{id:'trash-c',name:'C',deletedAt:1});state.busy=true;$('trashBtn').click();assert($('clearTrash').disabled,'purge enabled during model task');$('trashDialog').close();state.busy=false;$('trashBtn').click();$('clearTrash').click();await $('confirmPurge').onclick();assert(purged.join(',')==='trash-b,trash-c','bulk purge included live documents');assert(state.docs[0].id==='live'&&state.docs.length===1,'live document lost');$('trashDialog').close();});


for(const id of ['desktopTitlebar','appMenu','storageBtn','storageLocation','chooseChatFolder']){const e=document.createElement(id.includes('Btn')||id==='appMenu'||id==='chooseChatFolder'?'button':'div');e.id=id;document.getElementById('fixture').append(e);}
{const e=document.createElement('dialog');e.id='storageDialog';document.body.append(e);}
let chatCalls=[],archive={},chatFail=false,flushed=[];
window.paperDesktop={menu(){},async chats(action,input){chatCalls.push({action,input:structuredClone(input)});if(chatFail)return{ok:false,error:'Test directory unavailable'};if(action==='read')return{ok:true,...archive[input]};if(action==='choose')return{ok:true,cancelled:true};return{ok:true,folder:'Test conversations'};}};
const chatState={busy:false,docs:[]},desktop=createDesktopUI({state:chatState,toast:t=>{$('toast').textContent=t;},flush:async d=>flushed.push(structuredClone(d))});
await test('Desktop startup restores newer archived chats and exact source IDs',async()=>{const d={id:'restore',history:[],chatUpdatedAt:5};archive.restore={history:[{role:'assistant',text:'Restored',materials:[{id:'selection',blockId:'p7',text:'Evidence'}]}],savedAt:10};await desktop.load([d]);assert(d.history[0].materials[0].blockId==='p7'&&flushed.at(-1).chatUpdatedAt===10,'restore/source failed');});
await test('Older archive cannot overwrite newer local conversation',async()=>{const d={id:'stale',history:[{role:'user',text:'New local'}],chatUpdatedAt:20};archive.stale={history:[{role:'user',text:'Old file'}],savedAt:10};await desktop.load([d]);assert(d.history[0].text==='New local','stale overwrite');assert(chatCalls.at(-1).action==='save'&&chatCalls.at(-1).input.history[0].text==='New local','newer data not archived');});
await test('Queued snapshots retain content at save time and storage errors preserve local data',async()=>{const d={id:'queue',history:[{role:'user',text:'Original'}]};const p=desktop.save(d);d.history[0].text='Mutated';await p;assert(chatCalls.at(-1).input.history[0].text==='Original','mutable snapshot');chatFail=true;await desktop.load([d]);assert(d.history[0].text==='Mutated','error discarded local');await assertRejects(desktop.remove(['queue']));chatFail=false;});
async function assertRejects(p){let failed=false;try{await p;}catch{failed=true;}assert(failed,'failure not propagated');}
await test('Folder chooser cancellation preserves path and busy work blocks migration',async()=>{$('storageBtn').click();await Promise.resolve();assert($('storageLocation').textContent==='Test conversations','path missing');await $('chooseChatFolder').onclick();assert($('storageLocation').textContent==='Test conversations','cancel changed path');chatState.busy=true;const before=chatCalls.length;await $('chooseChatFolder').onclick();assert(chatCalls.length===before,'busy migration started');chatState.busy=false;$('storageDialog').close();});

out.textContent+=`\n${passed} passed, ${failed} failed`;document.title=`Tests: ${passed} passed, ${failed} failed`;
const seed=document.createElement('button');seed.textContent='打开旧版文献补图测试';seed.onclick=async()=>{const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('paper-space',1);req.onupgradeneeded=()=>req.result.createObjectStore('documents',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const doc={id:'v05-legacy',name:'0.5-图片测试.docx',type:'docx',...parsed,history:[],cards:[{blockId:'w2',page:1,title:'图片应留在原文中',category:'测试旁注',explanation:'补图后旁注应继续指向同一个段落。'}],code:[],lastPage:1,summary:'## 可核对的引用\n\n图片随原文保存。[w1] [w1] [w2] [w3] [w4] [w5]'};delete doc.figures;delete doc.imageVersion;await new Promise((resolve,reject)=>{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(doc);tx.oncomplete=resolve;tx.onerror=reject;});location.href='/';};document.body.append(seed);
