import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,readFile,readdir,writeFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createChatStore,chatSnapshot} from '../desktop/chat-store.mjs';
const doc={id:'../../arbitrary-file',name:'Example',history:[{role:'user',text:'Question'},{role:'assistant',text:'Answer',model:'local-test',materials:[{id:'p1',blockId:'pdf-block-7',kind:'原文',label:'Page 1',text:'Evidence',page:1}]}],apiKey:'SECRET',bytes:'ORIGINAL',chatUpdatedAt:100};
test('chat snapshots exclude credentials and original files, keep evidence',()=>{const s=chatSnapshot(doc);assert.equal(s.history[1].materials[0].text,'Evidence');assert(!JSON.stringify(s).includes('SECRET'));assert(!JSON.stringify(s).includes('ORIGINAL'));assert.equal(s.savedAt,100);assert.equal(s.history[1].materials[0].blockId,'pdf-block-7');assert.equal(s.history[1].materials[0].kind,'原文');});
test('conversation location persists across reopen, copies records and leaves old folder intact',async()=>{const root=await mkdtemp(join(tmpdir(),'paper-chats-')),store=createChatStore(root);await store.save(doc);const old=(await store.status()).folder;const target=join(root,'chosen');await mkdir(target);const next=await store.choose(target,[doc]);assert.equal(next.folder,join(target,'PaperSpace-Chats'));assert.equal((await readdir(old)).filter(f=>f.endsWith('.json')).length,1);const reopened=createChatStore(root);assert.deepEqual((await reopened.read(doc.id)).history,chatSnapshot(doc).history);assert.equal((await reopened.status()).folder,next.folder);assert((await readdir(next.folder)).every(n=>/^[a-f0-9]{64}\.json$/.test(n)));});
test('failed location migration keeps prior setting and prior readable records',async()=>{const root=await mkdtemp(join(tmpdir(),'paper-chats-fail-')),store=createChatStore(root);await store.save(doc);const before=(await store.status()).folder;const blocked=join(root,'blocked');await writeFile(blocked,'file');await assert.rejects(store.choose(blocked,[doc]));assert.equal((await store.status()).folder,before);assert.equal((await store.read(doc.id)).history[0].text,'Question');});
test('purge removes only owned conversation file and not original or unrelated files',async()=>{const root=await mkdtemp(join(tmpdir(),'paper-chats-purge-')),store=createChatStore(root);await store.save(doc);const folder=(await store.status()).folder;await writeFile(join(folder,'original.pdf'),'original');await store.remove([doc.id]);assert.deepEqual(await store.read(doc.id),{});assert.equal(await readFile(join(folder,'original.pdf'),'utf8'),'original');});
test('serialized saves preserve latest history after rapid changes',async()=>{const root=await mkdtemp(join(tmpdir(),'paper-chats-order-')),store=createChatStore(root);await Promise.all([store.save(doc),store.save({...doc,history:[{role:'user',text:'Newest'}],chatUpdatedAt:200})]);assert.equal((await store.read(doc.id)).history[0].text,'Newest');assert.equal((await store.read(doc.id)).savedAt,200);});
