// Isolated regression fixture: explicitly acknowledge the notice before exercising the app.
import {saveUsageConsent} from '/usage-consent.mjs';saveUsageConsent(localStorage);
import * as pdfjs from '/vendor/pdfjs/build/pdf.mjs';import {extractPdfParagraphs} from '/pdf-layout.mjs';import {doclingUnits,mapDoclingPage} from '/docling-layout.mjs';import {pdfBlockSpans} from '/pdf-text.mjs';import {sourceAtoms} from '/structure.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/build/pdf.worker.mjs';
const out=document.getElementById('results');let passed=0,failed=0;const assert=(v,m)=>{if(!v)throw Error(m);};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label='condition',timeout=12000){const start=Date.now();while(Date.now()-start<timeout){if(await fn())return;await sleep(40);}throw Error('Timeout '+label);}
async function test(name,fn){try{await fn();passed++;out.textContent+=`\nPASS ${name}`;}catch(e){failed++;out.textContent+=`\nFAIL ${name}: ${e.message}`;}}
const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space');r.onupgradeneeded=()=>r.result.createObjectStore('documents',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const bytes=await(await fetch('/fixture.pdf')).arrayBuffer(),pdf=await pdfjs.getDocument({data:bytes.slice(0),standardFontDataUrl:'/vendor/pdfjs/standard_fonts/'}).promise;const blocks=[];
const parseResponse=await fetch('/api/pdf/parse',{method:'POST',headers:{'Content-Type':'application/pdf'},body:bytes});const actualParse=await parseResponse.json();if(!parseResponse.ok)throw Error(actualParse.error);
for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),v=p.getViewport({scale:1}),c=await p.getTextContent({includeMarkedContent:true});blocks.push(...mapDoclingPage(doclingUnits(actualParse),c,v,n));}
const docId='v09-isolated-'+Date.now(),body=blocks.filter(b=>b.page===1&&!b.heading&&!b.artifact),original=body[0];
const fixture={id:docId,name:'纸间 0.9 · 公开测试段落.pdf',type:'pdf',bytes,blocks,pages:pdf.numPages,parser:'docling',doclingLayoutVersion:1,outline:[],history:[{role:'user',text:'Legacy question'},{role:'assistant',text:'Legacy answer',materials:[{...original,label:'Legacy source'}]}],cards:[{blockId:original.id,page:1,title:'历史旁注',explanation:'测试历史来源'}],summary:'',code:[],lastPage:1,chatUpdatedAt:1};
await new Promise((resolve,reject)=>{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(fixture);tx.oncomplete=resolve;tx.onerror=reject;});db.close();
localStorage.setItem('paper-space-active-doc',docId);localStorage.setItem('paper-space-seeded','1');localStorage.setItem('paper-space-models',JSON.stringify({profiles:[{id:'isolated-mock',name:'本机模拟模型',baseUrl:'http://127.0.0.1:4349/v1',format:'openai',model:'v09-mock',models:[{id:'v09-mock',name:'本机模拟'}]}],activeId:'isolated-mock'}));
const frame=document.createElement('iframe');frame.src='/';document.getElementById('frame').append(frame);const $=id=>frame.contentDocument.getElementById(id);
async function saved(){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const d=await new Promise((resolve,reject)=>{const r=db.transaction('documents').objectStore('documents').get(docId);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});db.close();return d;}
const clickText=(selector,text)=>{const el=[...frame.contentDocument.querySelectorAll(selector)].find(e=>e.textContent.includes(text));if(!el)throw Error('Missing '+text);el.click();return el;};const requests=async()=>await(await fetch('/test-requests')).json();
await until(()=>$('conversationBtn')&&$('startupScreen')?.hidden&&$('readingContent').querySelector('.paragraph-note'),'app ready',30000);
await test('IndexedDB v1 upgrades in real app and preserves legacy conversation',async()=>{const d=await saved();assert(d.conversationVersion===1&&d.conversations.length===1,'not migrated');assert(d.conversations[0].name==='历史对话','wrong name');assert(d.conversations[0].history[1].materials[0].text===original.text,'source lost');});
let first,second;
await test('New session retains legacy history; request uses current session only',async()=>{$('newChatBtn').click();await until(async()=>(await saved()).conversations.length===2);first=(await saved()).activeConversationId;$('question').value='SESSION-A question';$('sendBtn').click();await until(()=>$('stopBtn').hidden);const req=(await requests()).at(-1);assert(!JSON.stringify(req).includes('Legacy question'),'legacy leak');assert((await saved()).conversations[0].history.length===2,'legacy lost');});
await test('Busy request blocks switches and saves to captured owner',async()=>{$('newChatBtn').click();await until(async()=>(await saved()).conversations.length===3);second=(await saved()).activeConversationId;$('question').value='SESSION-B question';$('sendBtn').click();await until(()=>!$('stopBtn').hidden);$('newChatBtn').click();$('conversationBtn').click();clickText('.conversation-row .conversation-open','历史对话');assert($('toast').textContent.includes('停止'),'no guard');$('conversationsDialog').close();await until(()=>$('stopBtn').hidden);const d=await saved();assert(d.activeConversationId===second&&d.conversations.length===3,'switched during request');assert(d.conversations.find(c=>c.id===second).history.at(-1).text.includes('SESSION-B'),'answer misplaced');assert(!JSON.stringify((await requests()).at(-1)).includes('SESSION-A'),'other session leaked');});
await test('Rename, content search, confirmed soft deletion and restoration',async()=>{$('conversationBtn').click();const row=[...$('conversationList').children].find(e=>e.textContent.includes('当前'));[...row.querySelectorAll('button')].find(e=>e.textContent==='重命名').click();$('conversationName').value='结果复核';$('saveConversationName').click();await until(()=>$('renameConversationDialog').open===false);$('conversationSearch').value='SESSION-A';$('conversationSearch').dispatchEvent(new Event('input'));assert($('conversationList').children.length===1,'search incorrect');[...$('conversationList').querySelectorAll('button')].find(b=>b.textContent==='删除').click();assert(!(await saved()).conversations.find(c=>c.id===first).deletedAt,'deleted before confirmation');$('confirmConversationDelete').click();await until(()=>$('deleteConversationDialog').open===false);$('conversationSearch').value='';$('deletedConversations').checked=true;$('deletedConversations').dispatchEvent(new Event('change'));$('conversationList').querySelector('.conversation-open').click();await until(()=>$('conversationsDialog').open===false);assert(!(await saved()).conversations.find(c=>c.id===first).deletedAt,'restore failed');assert((await saved()).conversations.find(c=>c.id===second).name==='结果复核','rename lost');});
await test('Sessions and active choice survive full reload',async()=>{frame.contentWindow.location.reload();await sleep(150);await until(()=>$('conversationBtn')&&$('startupScreen')?.hidden&&$('readingContent').querySelector('.paragraph-note'),'reload',30000);assert($('chatMessages').textContent.includes('SESSION-A'),'active history not restored');assert((await saved()).conversations.length===3,'session lost');});
let mergedId;
await test('PDF merge retains all items and archives old note sources',async()=>{clickText('.pdf-paragraph-notice button','结构校正');$('structureBlock').value=original.id;$('structureBlock').dispatchEvent(new Event('change'));$('mergeStructure').click();await until(async()=>(await saved()).blocks.some(b=>b.manual));await until(()=>$('structureText').textContent.includes(body[1].text));const d=await saved(),m=d.blocks.find(b=>b.manual);mergedId=m.id;assert(m.text===body[0].text+'\n\n'+body[1].text,'text changed');assert(JSON.stringify(m.itemIndices)===JSON.stringify([...body[0].itemIndices,...body[1].itemIndices]),'items changed');assert(d.archivedCards[0].sourceText===original.text,'old source lost');assert($('structureText').textContent===m.text,'preview differs');});
await test('Merged highlight excludes neighbours and marks each admitted item',async()=>{$('previewStructure').click();const d=await saved(),m=d.blocks.find(b=>b.id===mergedId),page=$('readingContent').querySelector('.pdf-page');await until(()=>page.querySelector('.source-highlight'));const selected=pdfBlockSpans(page,m),neighbour=pdfBlockSpans(page,body[2]);assert(selected.every(s=>!neighbour.includes(s)),'neighbour selected');assert(page.querySelectorAll('.source-highlight').length===selected.length,'wrong mark count');});
await test('Boundary split retains exact text with exclusive items',async()=>{clickText('.pdf-paragraph-notice button','结构校正');$('structureBlock').value=mergedId;$('structureBlock').dispatchEvent(new Event('change'));$('splitBoundary').value=String(sourceAtoms(body[0]).length);$('splitStructure').click();await until(async()=>!(await saved()).blocks.some(b=>b.id===mergedId));await until(()=>$('structureText').textContent===body[0].text);const d=await saved(),parts=d.blocks.filter(b=>b.manual);assert(parts[0].text===body[0].text&&parts[1].text===body[1].text,'lossy split');assert(!parts[0].itemIndices.some(n=>parts[1].itemIndices.includes(n)),'overlap');});
await test('Range preview equals actual model input and note source',async()=>{const before=await saved(),target=before.blocks.find(b=>b.manual);assert(sourceAtoms(target).length>1,'fixture lacks mapped lines');$('structureBlock').value=target.id;$('structureBlock').dispatchEvent(new Event('change'));$('rangeStart').value='0';$('rangeEnd').value='0';$('rangeEnd').dispatchEvent(new Event('change'));const preview=$('rangePreview').textContent;$('adjustStructure').click();await until(async()=>!(await saved()).blocks.some(b=>b.id===target.id));const d=await saved(),range=d.blocks.find(b=>b.manual);assert(range.text===preview,'range differs');await until(()=>$('readingContent').querySelector(`[data-block-id="${range.id}"].paragraph-note`));$('structureDialog').close();$('readingContent').querySelector(`[data-block-id="${range.id}"].paragraph-note`).click();await until(()=>$('annotationDrawer'));assert((await requests()).at(-1).messages.at(-1).content.endsWith(preview),'input differs');assert($('annotationDrawer').querySelector('pre').textContent===preview,'note differs');});
await test('Corrections and undo survive reload; restore automatic is reversible',async()=>{frame.contentWindow.location.reload();await sleep(150);await until(()=>$('conversationBtn')&&$('startupScreen')?.hidden&&$('readingContent').querySelector('.paragraph-note'),'reload',30000);const count=(await saved()).blocks.length;clickText('.pdf-paragraph-notice button','结构校正');assert(!$('undoStructure').disabled,'undo lost');$('undoStructure').click();await until(async()=>(await saved()).blocks.length<count);await until(()=>$('structureDialog').getAttribute('aria-busy')!=='true');$('restoreStructure').click();await until(async()=>(await saved()).blocks.every(b=>!b.manual));await until(()=>$('structureDialog').getAttribute('aria-busy')!=='true');$('undoStructure').click();await until(async()=>(await saved()).blocks.some(b=>b.manual));await until(()=>$('structureDialog').getAttribute('aria-busy')!=='true');$('structureDialog').close();});
await test('Historical evidence keeps old text and source after correction',async()=>{$('conversationBtn').click();clickText('.conversation-open','历史对话');await until(()=>$('conversationsDialog').open===false);const d=await saved();assert(d.legacyBlocks.some(b=>b.id===original.id&&b.text===original.text),'old source unavailable');assert(d.conversations[0].history[1].materials[0].text===original.text,'snapshot changed');});
await test('Actual offline reparse retains corrections and historical snapshots',async()=>{const before=await saved(),ids=before.blocks.map(b=>b.id);clickText('.pdf-paragraph-notice button','重新识别');await until(()=>[...frame.contentDocument.querySelectorAll('.pdf-paragraph-notice button')].some(b=>b.textContent==='识别中…'));await until(()=>![...frame.contentDocument.querySelectorAll('.pdf-paragraph-notice button')].some(b=>b.textContent==='识别中…'),'background reparse',30000);assert(!frame.contentDocument.querySelector('.pdf-page-hint').textContent.includes('未完成'),'recognition failed');const after=await saved();assert(JSON.stringify(after.blocks.map(b=>b.id))===JSON.stringify(ids),'corrections discarded');assert(after.archivedCards.length===before.archivedCards.length,'old notes lost');});
out.textContent+=`\n\n${passed} passed, ${failed} failed`;document.title=`v0.9: ${passed} passed, ${failed} failed`;
