// Isolated regression fixture: explicitly acknowledge the notice before exercising the app.
import {saveUsageConsent} from '/usage-consent.mjs';saveUsageConsent(localStorage);
import {readingUnit} from '/reading-units.mjs';
import * as pdfjs from '/vendor/pdfjs/build/pdf.mjs';import {extractPdfParagraphs} from '/pdf-layout.mjs';import {doclingUnits,mapDoclingPage} from '/docling-layout.mjs';import {pdfBlockSpans,selectedPdfItems} from '/pdf-text.mjs';import {sourceAtoms} from '/structure.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/build/pdf.worker.mjs';
const out=document.getElementById('results');let passed=0,failed=0;const assert=(v,m)=>{if(!v)throw Error(m);};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label='condition',timeout=12000){const start=Date.now();while(Date.now()-start<timeout){if(await fn())return;await sleep(40);}throw Error('Timeout '+label);}
async function test(name,fn){try{await fn();passed++;out.textContent+=`\nPASS ${name}`;}catch(e){failed++;out.textContent+=`\nFAIL ${name}: ${e.message}`;}}
const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space');r.onupgradeneeded=()=>r.result.createObjectStore('documents',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const bytes=await(await fetch('/fixture.pdf')).arrayBuffer(),pdf=await pdfjs.getDocument({data:bytes.slice(0),standardFontDataUrl:'/vendor/pdfjs/standard_fonts/'}).promise;const blocks=[];
const parseResponse=await fetch('/api/pdf/parse',{method:'POST',headers:{'Content-Type':'application/pdf'},body:bytes});const actualParse=await parseResponse.json();if(!parseResponse.ok)throw Error(actualParse.error);
for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),v=p.getViewport({scale:1}),c=await p.getTextContent({includeMarkedContent:true});blocks.push(...mapDoclingPage(doclingUnits(actualParse),c,v,n));}
const docId='v091-isolated-'+Date.now(),body=blocks.filter(b=>b.page===1&&!b.heading&&!b.artifact),original=body[0];
const fixture={id:docId,name:'纸间 0.9 · 公开测试段落.pdf',type:'pdf',bytes,blocks:blocks.filter(b=>b!==body[1]).map(b=>b===body[2]?{...b,artifact:true}:b===body[3]?{...b,continuation:true,text:'Previous-page-only sentence. '+b.text}:b),pages:pdf.numPages,parser:'docling',doclingLayoutVersion:1,outline:[],history:[{role:'user',text:'Legacy question'},{role:'assistant',text:'Legacy answer',materials:[{...original,label:'Legacy source'}]}],cards:[{blockId:original.id,page:1,title:'历史旁注',explanation:'测试历史来源'}],summary:'',code:[],lastPage:1,chatUpdatedAt:1};
await new Promise((resolve,reject)=>{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(fixture);tx.oncomplete=resolve;tx.onerror=reject;});db.close();
localStorage.setItem('paper-space-active-doc',docId);localStorage.setItem('paper-space-seeded','1');localStorage.setItem('paper-space-models',JSON.stringify({profiles:[{id:'isolated-mock',name:'本机模拟模型',baseUrl:'http://127.0.0.1:4352/v1',format:'openai',model:'v09-mock',models:[{id:'v09-mock',name:'本机模拟'}]}],activeId:'isolated-mock'}));
const frame=document.createElement('iframe');frame.src='/';document.getElementById('frame').append(frame);const $=id=>frame.contentDocument.getElementById(id);
async function saved(){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const d=await new Promise((resolve,reject)=>{const r=db.transaction('documents').objectStore('documents').get(docId);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});db.close();return d;}
const clickText=(selector,text)=>{const el=[...frame.contentDocument.querySelectorAll(selector)].find(e=>e.textContent.includes(text));if(!el)throw Error('Missing '+text);el.click();return el;};const requests=async()=>await(await fetch('/test-requests')).json();
await until(()=>$('conversationBtn')&&$('startupScreen')?.hidden&&$('readingContent').querySelector('.paragraph-note'),'app ready',30000);

await test('Conversation checkbox stays beside its single-line label; new session control works',async()=>{$('conversationBtn').click();const cb=$('deletedConversations').getBoundingClientRect(),label=$('deletedConversations').nextElementSibling.getBoundingClientRect();assert(cb.width===15&&label.left-cb.right<10,'checkbox stretched');assert(label.height<24,'label wrapped');$('newManagedConversation').click();await until(()=>$('conversationsDialog').open===false);assert((await saved()).conversations.length===2,'new session lost');});
await test('Conversation dialog fits narrow and desktop widths without horizontal overflow',async()=>{frame.style.width='390px';await sleep(250);$('conversationBtn').click();const d=$('conversationsDialog');assert(d.getBoundingClientRect().width<=390,'dialog exceeds viewport');assert(d.scrollWidth<=d.clientWidth+1,'horizontal overflow');assert($('deletedConversations').nextElementSibling.getBoundingClientRect().height<24,'label wrapped');d.close();frame.style.width='1480px';await sleep(400);await until(()=>$('readingContent').querySelector('.pdf-paragraph-notice')&&$('readingContent').querySelector('.textLayer span'),'page after resize');});
await test('Recovery inventory finds genuinely missing, misclassified and continuation paragraphs',async()=>{clickText('.pdf-paragraph-notice button','补充漏识别');const text=$('recoveryCandidate').textContent;assert(text.includes('未纳入识别结果'),'missing gap');assert(text.includes('被识别为页眉'),'misclassified missing');assert(text.includes('跨页续段'),'continuation missing');$('structureDialog').close();});
function selectItems(indices,{partial=false}={}){const spans=pdfBlockSpans($('readingContent').querySelector('.pdf-page'),{page:1,itemIndices:indices});assert(spans.length,'no spans');const range=frame.contentDocument.createRange();range.setStart(spans[0].firstChild,partial?2:0);range.setEnd(spans.at(-1).firstChild,spans.at(-1).textContent.length-(partial?2:0));const selection=frame.contentWindow.getSelection();selection.removeAllRanges();selection.addRange(range);$('readingContent').dispatchEvent(new frame.contentWindow.MouseEvent('mouseup',{button:0,bubbles:true}));return selectedPdfItems(selection,$('readingContent').querySelector('.pdf-page'));}
let recovered,preview;
await test('Native selection captures missing items and expands partial text items for a reviewable preview',async()=>{const selected=selectItems(body[1].itemIndices,{partial:true});assert(JSON.stringify(selected)===JSON.stringify(body[1].itemIndices),'selection crossed a neighbour');assert(!$('recoverSelection').hidden,'missing selection entry');$('recoverSelection').click();assert($('structureDialog').open&&!$('structureRecoverPanel').hidden,'recovery not opened');preview=$('recoveryText').textContent;assert(preview.startsWith(body[1].text.slice(0,20)),'partial item was cut');assert(!$('applyRecovery').disabled,'selection refused');});
await test('Applying recovery adds a note marker and highlights only exact native items',async()=>{$('applyRecovery').click();await until(async()=>(await saved()).blocks.some(b=>b.recovered));await until(()=>$('structureText').textContent===preview&&$('structureDialog').getAttribute('aria-busy')!=='true');recovered=(await saved()).blocks.find(b=>b.recovered);assert(recovered.text===preview,'saved text differs');assert(JSON.stringify(recovered.itemIndices)===JSON.stringify(body[1].itemIndices),'items differ');$('previewStructure').click();const page=$('readingContent').querySelector('.pdf-page');assert(page.querySelectorAll('.source-highlight').length===body[1].itemIndices.length,'wrong highlights');assert($('readingContent').querySelector('[data-block-id="'+recovered.id+'"].paragraph-note'),'marker missing');});
await test('Recovered note uses the exact reviewed source and excludes neighbouring paragraphs',async()=>{frame.contentWindow.getSelection().removeAllRanges();$('readingContent').querySelector('[data-block-id="'+recovered.id+'"].paragraph-note').click();await until(()=>$('annotationDrawer'),'note drawer (toast: '+$('toast').textContent+')',30000);const req=(await requests()).at(-1);assert(req.messages.at(-1).content==='只解读下列一个原文段落：\n'.replace('\\n','\n')+preview,'model source mismatch');assert($('annotationDrawer').querySelector('pre').textContent===preview,'note source mismatch');const card=(await saved()).cards.find(c=>c.blockId===recovered.id);assert(JSON.stringify(card.sourceSnapshot.itemIndices)===JSON.stringify(recovered.itemIndices),'snapshot mismatch');});
await test('Selecting an already admitted paragraph cannot silently duplicate or replace it',async()=>{selectItems(body[1].itemIndices);$('recoverSelection').click();assert($('applyRecovery').disabled,'duplicate allowed');assert($('recoveryReason').textContent.includes('已有解读段落'),'missing explanation');$('structureDialog').close();});
async function admitHidden(id){clickText('.pdf-paragraph-notice button','补充漏识别');$('recoveryCandidate').value='hidden:'+id;$('recoveryCandidate').dispatchEvent(new Event('change'));const text=$('recoveryText').textContent;$('applyRecovery').click();await until(async()=>!(await saved()).blocks.some(b=>b.id===id));await until(()=>$('structureText').textContent===text);$('structureDialog').close();return text;}
await test('Misclassified text becomes an active paragraph with unchanged original neighbours',async()=>{const text=await admitHidden(body[2].id);const d=await saved();assert(d.blocks.some(b=>b.recovered&&b.text===text&&!b.artifact),'not admitted');assert(d.blocks.find(b=>b.id===body[0].id).text===body[0].text,'neighbour changed');});
await test('Continuation admission uses only current page, retaining the old complete source',async()=>{const text=await admitHidden(body[3].id);assert(!text.includes('Previous-page-only'),'previous page duplicated');const d=await saved();assert(d.legacyBlocks.find(b=>b.id===body[3].id).text.includes('Previous-page-only'),'historical source lost');});
await test('Recovery persists across reload and undo/restore, then survives actual offline reparse',async()=>{const expected=(await saved()).blocks.filter(b=>b.recovered).length;frame.contentWindow.location.reload();await sleep(150);await until(()=>$('startupScreen')?.hidden&&$('readingContent')?.querySelector('.paragraph-note'),'reload',30000);assert((await saved()).blocks.filter(b=>b.recovered).length===expected,'reload lost recovery');clickText('.pdf-paragraph-notice button','结构校正');$('undoStructure').click();await until(async()=>(await saved()).blocks.filter(b=>b.recovered).length===expected-1);await until(()=>$('structureDialog').getAttribute('aria-busy')!=='true');$('restoreStructure').click();await until(async()=>(await saved()).blocks.every(b=>!b.recovered));await until(()=>$('structureDialog').getAttribute('aria-busy')!=='true');$('undoStructure').click();await until(async()=>(await saved()).blocks.some(b=>b.recovered));await until(()=>$('structureDialog').getAttribute('aria-busy')!=='true');$('structureDialog').close();const before=(await saved()).blocks.map(b=>b.id);clickText('.pdf-paragraph-notice button','重新识别');await until(()=>[...frame.contentDocument.querySelectorAll('.pdf-paragraph-notice button')].some(b=>b.textContent==='识别中…'));await until(()=>![...frame.contentDocument.querySelectorAll('.pdf-paragraph-notice button')].some(b=>b.textContent==='识别中…'),'background reparse',30000);assert(!frame.contentDocument.querySelector('.pdf-page-hint').textContent.includes('未完成'),'recognition failed');assert(JSON.stringify((await saved()).blocks.map(b=>b.id))===JSON.stringify(before),'reparse discarded recovery');});
await test('Public Transformer page 7 exposes the complete cross-page unit with exact current-page source',async()=>{
  const raw=await(await fetch('/sample-layout.json')).json(),sampleBytes=await(await fetch('/demo.pdf')).arrayBuffer(),samplePdf=await pdfjs.getDocument({data:sampleBytes.slice(0),standardFontDataUrl:'/vendor/pdfjs/standard_fonts/'}).promise,sampleBlocks=[];
  for(let n=1;n<=samplePdf.numPages;n++){const page=await samplePdf.getPage(n);sampleBlocks.push(...mapDoclingPage(doclingUnits(raw),await page.getTextContent({includeMarkedContent:true}),page.getViewport({scale:1}),n));}
  const continuation=sampleBlocks.find(b=>b.page===7&&b.continuation&&b.text.includes('length n is smaller'));assert(continuation,'public sample did not reproduce');
  const sampleId='v091-public-'+Date.now(),sample={id:sampleId,name:'Attention Is All You Need · 公开示例.pdf',type:'pdf',bytes:sampleBytes,blocks:sampleBlocks,pages:samplePdf.numPages,parser:'docling',doclingLayoutVersion:1,outline:[],history:[],cards:[],summary:'',code:[],lastPage:7};
  const database=await new Promise(resolve=>{const r=indexedDB.open('paper-space');r.onsuccess=()=>resolve(r.result);});await new Promise(resolve=>{const tx=database.transaction('documents','readwrite');tx.objectStore('documents').put(sample);tx.oncomplete=resolve;});database.close();localStorage.setItem('paper-space-active-doc',sampleId);frame.contentWindow.location.reload();await sleep(150);await until(()=>$('startupScreen')?.hidden&&$('pageInput')?.value==='7'&&$('readingContent').querySelector('.paragraph-note'),'sample ready',30000);
  const unit=readingUnit(sample,continuation.id);assert(unit.crossPage,'public cross-page source not linked');assert(unit.text.includes('As noted in Table')&&unit.text.includes('future work'),'full paragraph lost');assert($('readingContent').querySelector('.paragraph-note[data-block-id="'+unit.id+'"]'),'continuation still has no marker');
  clickText('.pdf-paragraph-notice button','补充漏识别');assert(![...$('recoveryCandidate').options].some(o=>o.value==='hidden:'+continuation.id),'readable continuation reported missing');$('structureDialog').close();
  clickText('.pdf-paragraph-notice button','跨页段落');clickText('#crossPageDialog button','查看第 7 页');await until(()=>$('readingContent').querySelectorAll('.source-highlight').length===continuation.itemIndices.length,'native highlight');

});
out.textContent+='\n\n'+passed+' passed, '+failed+' failed';document.title='v0.9.1: '+passed+' passed, '+failed+' failed';
