import * as pdfjs from '/vendor/pdfjs/build/pdf.mjs';import {extractPdfParagraphs} from '/pdf-layout.mjs';import {doclingUnits,mapDoclingPage} from '/docling-layout.mjs';import {pdfBlockSpans} from '/pdf-text.mjs';import {sourceAtoms} from '/structure.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/build/pdf.worker.mjs';
const out=document.getElementById('results');let passed=0,failed=0;const assert=(v,m)=>{if(!v)throw Error(m);};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label='condition',timeout=12000){const start=Date.now();while(Date.now()-start<timeout){if(await fn())return;await sleep(40);}throw Error('Timeout '+label);}
async function test(name,fn){try{await fn();passed++;out.textContent+=`\nPASS ${name}`;}catch(e){failed++;out.textContent+=`\nFAIL ${name}: ${e.message}`;}}
const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space');r.onupgradeneeded=()=>r.result.createObjectStore('documents',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const bytes=await(await fetch('/fixture.pdf')).arrayBuffer(),pdf=await pdfjs.getDocument({data:bytes.slice(0),standardFontDataUrl:'/vendor/pdfjs/standard_fonts/'}).promise;const blocks=[];
const parseResponse=await fetch('/api/pdf/parse',{method:'POST',headers:{'Content-Type':'application/pdf'},body:bytes});const actualParse=await parseResponse.json();if(!parseResponse.ok)throw Error(actualParse.error);
for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),v=p.getViewport({scale:1}),c=await p.getTextContent({includeMarkedContent:true});blocks.push(...mapDoclingPage(doclingUnits(actualParse),c,v,n));}
const docId='v092-isolated-'+Date.now(),body=blocks.filter(b=>b.page===1&&!b.heading&&!b.artifact),original=body[0];
const fixture={id:docId,name:'纸间 0.9 · 公开测试段落.pdf',type:'pdf',bytes,blocks,pages:pdf.numPages,parser:'docling',doclingLayoutVersion:1,outline:[],history:[{role:'user',text:'Legacy question'},{role:'assistant',text:'Legacy answer',materials:[{...original,label:'Legacy source'}]}],cards:[{blockId:original.id,page:1,title:'历史旁注',explanation:'测试历史来源'}],summary:'',code:[],lastPage:1,chatUpdatedAt:1};
fixture.structure={version:1,autoBlocks:structuredClone(blocks),undo:[],operations:[],conflict:null};fixture.archivedCards=Array.from({length:7},(_,i)=>({blockId:original.id,page:1,title:'隔离旧版旁注 '+(i+1),explanation:'公开测试记录',sourceText:original.text,sourceSnapshot:original}));
await new Promise((resolve,reject)=>{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(fixture);tx.oncomplete=resolve;tx.onerror=reject;});db.close();
localStorage.setItem('paper-space-active-doc',docId);localStorage.setItem('paper-space-seeded','1');localStorage.setItem('paper-space-models',JSON.stringify({profiles:[{id:'isolated-mock',name:'本机模拟模型',baseUrl:'http://127.0.0.1:4362/v1',format:'openai',model:'v09-mock',models:[{id:'v09-mock',name:'本机模拟'}]}],activeId:'isolated-mock'}));
const frame=document.createElement('iframe');frame.src='/';document.getElementById('frame').append(frame);const $=id=>frame.contentDocument.getElementById(id);
async function saved(){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const d=await new Promise((resolve,reject)=>{const r=db.transaction('documents').objectStore('documents').get(docId);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});db.close();return d;}
const clickText=(selector,text)=>{const el=[...frame.contentDocument.querySelectorAll(selector)].find(e=>e.textContent.includes(text));if(!el)throw Error('Missing '+text);el.click();return el;};const requests=async()=>await(await fetch('/test-requests')).json();
await until(()=>$('conversationBtn')&&$('readingContent').querySelector('.paragraph-note'),'app ready',30000);

await test('Real PDF first screen settles before startup releases keyboard and pointer access',async()=>{await until(()=>$('startupScreen').hidden,'startup complete');assert(!$('readingContent').closest('.app').inert,'workspace still inert');assert($('readingContent').querySelector('.pdf-page canvas'),'canvas missing');assert($('readingContent').querySelector('.textLayer span[data-item-index]'),'text not rendered');assert($('startupScreen').dataset.state==='ready','not readiness driven');assert($('readingContent').closest('.app').getAttribute('aria-busy')==='false','busy state stuck');});
await test('Toolbar groups actions tightly and keeps correction status with page count',async()=>{const d=frame.contentDocument,bar=d.querySelector('.pdf-paragraph-notice'),actions=d.querySelector('.pdf-page-actions'),edit=d.querySelector('.pdf-edit-actions');assert(d.querySelector('.pdf-page-summary').textContent.includes('已校正'),'status not with count');assert(actions.contains(edit)&&actions.querySelector('.pdf-secondary-actions'),'groups missing');const btn=edit.querySelectorAll('button'),a=btn[0].getBoundingClientRect(),b=btn[1].getBoundingClientRect();assert(b.left-a.right<=8,'primary controls spread out');assert(bar.scrollWidth<=bar.clientWidth+1,'toolbar overflow');assert(bar.textContent.includes('旧版旁注 7'),'archive missing');});
await test('Grouped buttons still open the correct structure, recovery and archived notes views',async()=>{clickText('.pdf-paragraph-notice button','结构校正');assert($('structureDialog').open&&!$('structureAdjustPanel').hidden,'adjust wrong');$('structureDialog').close();clickText('.pdf-paragraph-notice button','补充漏识别');assert($('structureDialog').open&&!$('structureRecoverPanel').hidden,'recovery wrong');$('structureDialog').close();clickText('.pdf-paragraph-notice button','旧版旁注');assert($('legacyNotesDialog').open&&$('legacyNotesList').textContent.includes('隔离旧版旁注 7'),'archive wrong');$('legacyNotesDialog').close();});
await test('Toolbar stays usable in narrow reader columns without horizontal scrolling',async()=>{for(const width of [1050,840,390]){frame.style.width=width+'px';await sleep(400);await until(()=>$('readingContent').querySelector('.pdf-paragraph-notice'),'toolbar after resize');const bar=$('readingContent').querySelector('.pdf-paragraph-notice');assert(bar.scrollWidth<=bar.clientWidth+1,'overflow at '+width);const buttons=[...bar.querySelectorAll('button')];assert(buttons.every(b=>b.getBoundingClientRect().width>20),'hidden controls at '+width);}frame.style.width='1480px';await sleep(400);});
const opening=document.createElement('iframe');opening.style.cssText='width:1100px;height:780px';document.getElementById('frame').append(opening);opening.src='/startup-case';
const boot=id=>opening.contentDocument?.getElementById(id);
await test('Opening animation covers incomplete content and holds focus until explicit readiness',async()=>{await until(()=>boot('startupScreen')&&boot('startupStatus').textContent.includes('还原'),'opening stage');await sleep(1500);assert(!boot('startupScreen').hidden,'opened before readiness');assert(opening.contentDocument.querySelector('.app').inert,'underlying controls interactive');const leaf=opening.contentDocument.querySelector('.startup-leaf-turn'),css=()=>opening.contentWindow.getComputedStyle(leaf);assert(css().animationName==='startup-page','page animation missing');const before=css().transform;await until(()=>css().transform!==before,'visible page motion',3500);});
await test('Slow startup shows an honest loading message, then releases on real completion',async()=>{await until(()=>boot('startupScreen').dataset.state==='slow','slow startup',10000);assert(boot('startupHint').textContent.includes('更久'),'slow hint missing');assert(!boot('startupScreen').hidden,'slow load revealed unfinished view');opening.contentDocument.dispatchEvent(new Event('fixture-ready'));await until(()=>boot('startupScreen').hidden,'ready transition');assert(!opening.contentDocument.querySelector('.app').inert,'still inaccessible');});
await test('Application module failure exposes a retry instead of an endless opening animation',async()=>{opening.src='/startup-case?mode=error';await until(()=>boot('startupScreen')?.dataset.state==='error','module failure');assert(!boot('startupRetry').hidden,'retry missing');assert(boot('startupHint').textContent.includes('记录会保留'),'failure text wrong');assert(opening.contentWindow.getComputedStyle(opening.contentDocument.querySelector('.startup-leaf-turn')).animationName==='none','error still animating');boot('startupRetry').click();await until(()=>boot('startupScreen')?.dataset.state==='error','retry failure again');});
opening.remove();out.textContent+='\n\n'+passed+' passed, '+failed+' failed';document.title='v0.9.2: '+passed+' passed, '+failed+' failed';
