// Isolated regression fixture: explicitly acknowledge the notice before exercising the app.
import {saveUsageConsent} from '/usage-consent.mjs';saveUsageConsent(localStorage);
import * as pdfjs from '/vendor/pdfjs/build/pdf.mjs';
import {readWordHTML,restoreWordTables,renderWordBlock} from '/word-import.mjs';
import {doclingUnits,mapDoclingPage} from '/docling-layout.mjs';import {pdfNavigation} from '/pdf-navigation.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/build/pdf.worker.mjs';
const out=document.getElementById('results');let passed=0,failed=0;const assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label='condition',timeout=15000){const start=Date.now();while(Date.now()-start<timeout){if(await fn())return;await sleep(40);}throw Error('Timeout '+label);}
async function test(name,fn){try{await fn();passed++;out.textContent+='\nPASS '+name;}catch(e){failed++;out.textContent+='\nFAIL '+name+': '+e.message;}}
async function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('documents'))r.result.createObjectStore('documents',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function put(doc){const db=await database();await new Promise((resolve,reject)=>{const t=db.transaction('documents','readwrite');t.objectStore('documents').put(doc);t.oncomplete=resolve;t.onerror=reject;});db.close();}
async function saved(id){const db=await database();const d=await new Promise((resolve,reject)=>{const r=db.transaction('documents').objectStore('documents').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=reject;});db.close();return d;}
const requestBaseline=(await(await fetch('/test-requests')).json()).length;
const mode=value=>fetch('/test-mode?value='+value);await mode('normal');
const bytes=await(await fetch('/fixture.pdf')).arrayBuffer(),pdf=await pdfjs.getDocument({data:bytes.slice(0),standardFontDataUrl:'/vendor/pdfjs/standard_fonts/'}).promise;
const response=await fetch('/api/pdf/parse',{method:'POST',headers:{'Content-Type':'application/pdf'},body:bytes}),layout=await response.json();if(!response.ok)throw Error(layout.error);
const blocks=[];for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n);blocks.push(...mapDoclingPage(doclingUnits(layout),await p.getTextContent({includeMarkedContent:true}),p.getViewport({scale:1}),n));}
const wordBytes=await(await fetch('/fixture.docx')).arrayBuffer(),converted=await mammoth.convertToHtml({arrayBuffer:wordBytes},{externalFileAccess:false}),word=readWordHTML(converted.value);
const stamp=Date.now(),wordId='v093-word-'+stamp,pdfId='v093-pdf-'+stamp,outlineId='v093-outline-'+stamp;
const base={cards:[],history:[],summary:'',code:[],lastPage:1};
const legacyWord={...base,...word,id:wordId,name:'合并单元格表格测试.docx',type:'docx',bytes:wordBytes,tableVersion:undefined,chapterVersion:undefined,blocks:word.blocks.map(({table,kind,headingLevel,...b})=>b),history:[{role:'user',text:'Keep my note'}],cards:[{blockId:word.blocks.find(b=>b.table).id,page:1,title:'Original table note',explanation:'Preserve this original table source'}]};
await put(legacyWord);await put({...base,id:pdfId,name:'后台识别公开测试-'+stamp+'.pdf',type:'pdf',bytes,blocks:[],pages:2,outline:[],parser:'geometry'});
const outlineBytes=await(await fetch('/outline.pdf')).arrayBuffer(),outlinePdf=await pdfjs.getDocument({data:outlineBytes.slice(0)}).promise;
await put({...base,id:outlineId,name:'章节范围测试-'+stamp+'.pdf',type:'pdf',bytes:outlineBytes,blocks:[],...await pdfNavigation(outlinePdf),parser:'docling',doclingLayoutVersion:1,lastPage:12});
localStorage.setItem('paper-space-seeded','1');localStorage.setItem('paper-space-active-doc',wordId);localStorage.removeItem('paper-space-models');
const frame=document.createElement('iframe');frame.src='/';document.getElementById('frame').append(frame);const $=id=>frame.contentDocument?.getElementById(id),q=s=>frame.contentDocument?.querySelector(s);
const clickText=(selector,text)=>{const e=[...frame.contentDocument.querySelectorAll(selector)].find(e=>e.textContent.includes(text));if(!e)throw Error('Missing '+text);e.click();return e;};
const ready=()=>until(()=>$('startupScreen')?.hidden&&($('readingContent')?.querySelector('.word-table')||q('.pdf-paragraph-notice')),'reader ready',30000);
await ready();
await test('Actual DOCX import retains cell grid, row/column spans and exact historical table text',async()=>{const b=word.blocks.find(b=>b.table);assert(b.table.rows.length===5,'rows missing');assert(b.table.rows.some(r=>r.cells.some(c=>c.rowSpan===2)),'row span lost');assert(b.table.rows.some(r=>r.cells.some(c=>c.colSpan===2)),'column span lost');assert(b.table.rows.some(r=>r.cells.some(c=>c.rowSpan===2&&c.text.includes('\n'))),'merged cell paragraphs collapsed');assert(q('.word-table td[rowspan="2"]')&&q('.word-table td[colspan="2"]'),'merged grid not rendered');const d=await saved(wordId);assert(d.blocks.find(x=>x.id===b.id).text===legacyWord.blocks.find(x=>x.id===b.id).text,'historical text changed');assert(d.cards[0].blockId===b.id&&d.history[0].text==='Keep my note','notes lost');assert(d.tableVersion===1&&d.chapterVersion===1,'migration not saved');assert(d.blocks.filter(b=>b.heading).every(b=>b.headingLevel),'legacy heading levels missing');});
await test('Table renderer keeps hostile HTML inert and wrong source restoration is rejected',()=>{const p=readWordHTML('<table><tr><th colspan="2">Header</th></tr><tr><td>&lt;img src=x onerror=alert(1)&gt;</td><td><a href="https://example.com">Link</a></td></tr></table>');const e=renderWordBlock(p.blocks[0],document);assert(!e.querySelector('img,a,script'),'unsafe HTML mounted');assert(e.querySelector('th').colSpan===2,'header span lost');let rejected=false;try{restoreWordTables(legacyWord,p);}catch{rejected=true;}assert(rejected,'wrong source overwritten');});
await test('Migrated table survives reload and narrow tables scroll within their own container',async()=>{frame.contentWindow.location.reload();await sleep(100);await ready();assert(q('.word-table'),'table not restored');frame.style.width='840px';await sleep(500);await until(()=>q('.word-table'));const wrap=q('.word-table-wrap');assert(wrap.scrollWidth>=wrap.clientWidth,'scroll container absent');assert(q('.paper-sheet').scrollWidth<=q('.paper-sheet').clientWidth+1,'table leaks from sheet');frame.style.width='1480px';await sleep(400);});
await test('PDF chapter stays active on pages 12/13 and targets Tables start without sidebar page labels',async()=>{clickText('.document-item','章节范围测试-'+stamp);await until(()=>q('.pdf-page')?.dataset.page==='12'&&q('.pdf-paragraph-notice'),'outline doc');const active=q('.outline-item.active');assert(active.textContent==='Tables'&&!q('.outline-page'),'chapter label incorrect');$('nextPage').click();await until(()=>q('.pdf-page')?.dataset.page==='13'&&q('.pdf-paragraph-notice'));assert(q('.outline-item.active').textContent.includes('Tables'),'page13 lost active range');q('.outline-item.active').click();await until(()=>q('.pdf-page')?.dataset.page==='11'&&q('.pdf-paragraph-notice'));assert($('pageInput').value==='11','section jump not at start');});
await mode('hold');
await test('Original PDF and selectable text are usable before delayed recognition; no global busy lock',async()=>{clickText('.document-item','后台识别公开测试-'+stamp);await until(()=>q('.pdf-page canvas')&&q('.textLayer span')&&q('.pdf-page-summary')?.textContent.includes('后台'),'original while parsing');assert($('stopBtn').hidden,'recognition blocks model controls');assert(q('.pdf-page')?.dataset.page==='1','wrong first page');assert((await saved(pdfId)).parser!=='docling','recognition already completed');await until(async()=>(await(await fetch('/test-stats')).json()).waiting>=1,'delayed recognition accepted');$('overviewBtn').click();assert($('toast').textContent.includes('等待后台'),'incomplete full overview allowed');});
await test('Background completion updates structure without replacing canvas or resetting reading position',async()=>{frame.style.height='600px';await sleep(500);await until(()=>q('.pdf-paragraph-notice'));$('nextPage').click();await until(()=>q('.pdf-page')?.dataset.page==='2'&&q('.pdf-paragraph-notice'));$('readerScroll').scrollTo({top:180,behavior:'instant'});await until(()=>$('readerScroll').scrollTop>=179,'scroll position settled');const scroll=$('readerScroll').scrollTop,canvas=q('.pdf-page canvas'),beforeTop=q('.pdf-page').getBoundingClientRect().top;await mode('normal');await until(async()=>(await saved(pdfId)).parser==='docling'&&!q('.pdf-page-summary').textContent.includes('后台'),'recognition committed',30000);assert(q('.pdf-page canvas')===canvas,'canvas replaced');assert($('pageInput').value==='2','page reset');assert(Math.abs(q('.pdf-page').getBoundingClientRect().top-beforeTop)<2,'visible reading position moved');assert(scroll>0&&$('readerScroll').scrollTop>0,'scroll reset: '+scroll+' -> '+$('readerScroll').scrollTop);frame.style.height='1000px';await sleep(500);await until(()=>q('.pdf-paragraph-notice'));});
let missingId,preview;
await test('Missing body prompts proactively and opens the exact source for review',async()=>{const doc=await saved(pdfId),body=doc.blocks.filter(b=>b.page===1&&!b.heading&&!b.artifact&&!b.continuation);missingId=body[1].id;doc.blocks=doc.blocks.filter(b=>b.id!==missingId);doc.lastPage=1;await put(doc);frame.contentWindow.location.reload();await sleep(100);await ready();assert(q('.pdf-gap-notice'),'no proactive hint');clickText('.pdf-gap-notice button','核对漏段');assert($('structureDialog').open&&!$('structureRecoverPanel').hidden,'not reviewing');preview=$('recoveryText').textContent;assert(preview.includes(body[1].text.slice(0,30)),'wrong candidate chosen');});
await test('Admitting a proposed gap updates markers and persists exact preview with reversible history',async()=>{$('applyRecovery').click();await until(async()=>(await saved(pdfId)).blocks.some(b=>b.recovered&&b.text===preview));await until(()=>$('structureText').textContent===preview);$('structureDialog').close();const d=await saved(pdfId),b=d.blocks.find(b=>b.recovered);assert(q('[data-block-id="'+b.id+'"].paragraph-note'),'missing marker');assert(d.structure.undo.length>0,'not reversible');assert(!q('.pdf-gap-notice'),'resolved hint remains');});
await test('Recognition waits for an open correction dialog and preserves edits on completion',async()=>{await mode('hold');clickText('.pdf-paragraph-notice button','重新识别');clickText('.pdf-paragraph-notice button','结构校正');await mode('normal');await until(()=>q('.pdf-page-summary').textContent.includes('已完成'),'waiting for dialog',30000);assert($('structureDialog').open,'dialog unexpectedly closed');$('structureDialog').close();await until(()=>!q('.pdf-page-summary').textContent.includes('已完成'));const d=await saved(pdfId);assert(d.blocks.some(b=>b.recovered&&b.text===preview),'manual recovery overwritten');assert(d.structure,'structure lost');});
await test('Recognition failure keeps original and manual edits readable, explicit retry recovers',async()=>{await mode('fail');const canvas=q('.pdf-page canvas');clickText('.pdf-paragraph-notice button','重新识别');await until(()=>q('.pdf-page-hint')?.textContent.includes('未完成'),'failure visible');assert(q('.pdf-page canvas')===canvas,'failure replaced original');assert((await saved(pdfId)).blocks.some(b=>b.recovered),'failure lost edits');await mode('normal');clickText('.pdf-paragraph-notice button','重新识别');await until(()=>!q('.pdf-page-hint')?.textContent.includes('未完成')&&!q('.pdf-page-summary')?.textContent.includes('后台'),'retry',30000);});
await test('Dismissed gap hints survive reload while manual recovery inventory stays available',async()=>{const d=await saved(pdfId);d.blocks=d.blocks.filter(b=>!b.recovered);d.structure=undefined;await put(d);frame.contentWindow.location.reload();await sleep(100);await ready();assert(q('.pdf-gap-notice'),'test missing gap');clickText('.pdf-gap-notice button','本页暂不提示');await until(()=>!q('.pdf-gap-notice'));frame.contentWindow.location.reload();await sleep(100);await ready();assert(!q('.pdf-gap-notice'),'dismiss not persisted');clickText('.pdf-paragraph-notice button','补充漏识别');assert($('recoveryCandidate').textContent.includes('未纳入识别结果'),'manual review lost dismissed candidate');$('structureDialog').close();});
await test('New PDF import opens the original before local recognition, and startup reload is also nonblocking',async()=>{await mode('hold');const dt=new frame.contentWindow.DataTransfer();dt.items.add(new frame.contentWindow.File([bytes],'新导入测试-'+stamp+'.pdf',{type:'application/pdf'}));$('fileInput').files=dt.files;$('fileInput').dispatchEvent(new frame.contentWindow.Event('change',{bubbles:true}));await until(()=>$('docTitle').textContent.includes('新导入测试')&&q('.pdf-page canvas')&&q('.textLayer span')&&q('.pdf-paragraph-notice'),'new import original');assert(q('.pdf-page-hint').textContent.includes('原文'),'no background status');frame.contentWindow.location.reload();await sleep(100);await ready();assert(q('.pdf-page canvas')&&q('.textLayer span'),'startup original absent');assert(q('.pdf-page-summary').textContent.includes('后台'),'startup waited for recognition');await mode('normal');await until(()=>!q('.pdf-page-summary').textContent.includes('后台'),'import completes',30000);});
assert((await(await fetch('/test-requests')).json()).length===requestBaseline,'unexpected model call');out.textContent+='\n'+passed+' passed, '+failed+' failed';document.title='Tests: '+passed+' passed, '+failed+' failed';
