import test from 'node:test';import assert from 'node:assert/strict';
import {pdfNavigation,outlineRange,activeOutline,physicalPage} from '../public/pdf-navigation.mjs';
import {createPdfBackground} from '../public/pdf-background.mjs';import {suspectedGaps} from '../public/pdf-recovery.mjs';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
test('Tables range is 11–13 and stays active on pages 12 and 13',()=>{const a=[{title:'References',page:9},{title:'Tables',page:11},{title:'Figure 1',page:14},{title:'Figure 2',page:15},{title:'Figure 3',page:16}];assert.deepEqual(outlineRange(a,1,16),{start:11,end:13});for(const p of [11,12,13])assert.equal(activeOutline(a,p),1);assert.equal(activeOutline(a,14),2);});
test('Nested outlines stop at sibling sections, numeric zero and indirect destinations both resolve',async()=>{const p={numPages:16,getPageLabels:async()=>['i',...Array.from({length:15},(_,i)=>String(i+1))],getOutline:async()=>[{title:'Front',dest:[0],items:[{title:'Nested',dest:[2]}]},{title:'Tables',dest:'tables'},{title:'Figure',dest:[{num:9}]}],getDestination:async()=>[10],getPageIndex:async()=>13};const n=await pdfNavigation(p);assert.deepEqual(n.outline.map(x=>x.page),[1,3,11,14]);assert.deepEqual(outlineRange(n.outline,0,16),{start:1,end:10});assert.equal(n.pageLabels[0],'i');});
test('Invalid and external destinations are omitted, physical pages remain integral and bounded',async()=>{const n=await pdfNavigation({numPages:3,getOutline:async()=>[{title:'web'},{title:'invalid',dest:[99]},{title:'last',dest:[2]}]});assert.deepEqual(n.outline.map(x=>x.page),[3]);assert.equal(physicalPage(1.6,3),1);assert.equal(physicalPage(10,3),3);assert.equal(physicalPage(NaN,3),1);});
test('Background requests deduplicate, stay pending through editing and apply the latest document state',async()=>{const gate=deferred(),idle=deferred(),d={id:'a',manual:0};let parses=0,applied;let ready=false;const runner=createPdfBackground({parse:()=>{parses++;return gate.promise;},changed(){},canApply:()=>ready,delay:()=>idle.promise,apply:async(doc,p)=>{applied={manual:doc.manual,result:p};}});const a=runner.start(d),b=runner.start(d);assert.equal(a,b);await Promise.resolve();assert.equal(parses,1);gate.resolve('parsed');await new Promise(r=>setImmediate(r));assert.equal(runner.status(d).phase,'waiting');d.manual=7;ready=true;idle.resolve();await a;assert.deepEqual(applied,{manual:7,result:'parsed'});assert.equal(runner.status(d),null);});
test('Background results stay with their document, deleted documents are not resurrected',async()=>{const gate=deferred(),a={id:'a'},b={id:'b'},applied=[];const r=createPdfBackground({parse:d=>d===a?gate.promise:Promise.resolve('b'),changed(){},apply:async d=>applied.push(d.id)});const pa=r.start(a);const pb=r.start(b);assert.equal(r.status(b).phase,'queued');a.deletedAt=1;gate.resolve('a');await pa;await pb;assert.deepEqual(applied,['b']);});
test('Background failures allow explicit retry without discarding the original or manual state',async()=>{let attempts=0;const d={id:'d',blocks:['original'],structure:{manual:true}};const r=createPdfBackground({parse:async()=>{if(!attempts++)throw Error('offline');return 'okay';},changed(){},apply:async()=>{}});assert.equal(await r.start(d),false);assert.equal(r.status(d).phase,'error');assert.equal(await r.start(d),true);assert.deepEqual(d.blocks,['original']);assert.equal(d.structure.manual,true);});
test('Gap hints include missing body and continuation but suppress headings, page numbers and margins',()=>{const texts=['12','A normal missing paragraph contains enough meaningful words to require review.','This continuation contains a meaningful sentence carried from the previous page.','Training','A very long running header that repeats on every page should never prompt a missing body warning.'];const runs=texts.map((text,i)=>({itemIndex:i,text,x:30,right:500,y:[785,180,300,400,12][i],bottom:[795,200,320,420,24][i]}));const source={docId:'d',fileFingerprint:'f',page:1,height:800,runs,groups:runs.map(r=>({itemIndices:[r.itemIndex]}))};const doc={id:'d',fileFingerprint:'f',parser:'docling',blocks:[{id:'c',page:1,text:texts[2],continuation:true,itemIndices:[2]},{id:'h',page:1,text:texts[3],heading:true,itemIndices:[3]}]};const gaps=suspectedGaps(doc,source);assert.equal(gaps.length,2);doc.pdfReview={dismissed:[gaps[0].key]};assert.equal(suspectedGaps(doc,source).length,1);doc.parser='geometry';assert.equal(suspectedGaps(doc,source).length,0);});

test('Sections starting on the same page do not inherit later siblings pages',()=>{const a=[{title:'Introduction',page:2,depth:0},{title:'Background',page:2,depth:0},{title:'Model',page:2,depth:0},{title:'Attention',page:3,depth:1},{title:'Why',page:6,depth:0}];assert.deepEqual(outlineRange(a,0,15),{start:2,end:2});assert.deepEqual(outlineRange(a,1,15),{start:2,end:2});assert.deepEqual(outlineRange(a,2,15),{start:2,end:5});});
