// Isolated regression fixture: explicitly acknowledge the notice before exercising the app.
import {saveUsageConsent} from '/usage-consent.mjs';saveUsageConsent(localStorage);
import * as pdfjs from '/vendor/pdfjs/build/pdf.mjs';import {extractPdfParagraphs} from '/pdf-layout.mjs';import {pdfNavigation} from '/pdf-navigation.mjs';import {readingUnits} from '/reading-units.mjs';import {pdfBlockSpans} from '/pdf-text.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/build/pdf.worker.mjs';
const out=document.getElementById('results');let passed=0,failed=0;const assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label='condition',timeout=15000){const t=Date.now();while(Date.now()-t<timeout){if(await fn())return;await sleep(40);}throw Error('Timeout '+label);}
async function test(name,fn){try{await fn();passed++;out.textContent+='\nPASS '+name;}catch(e){failed++;out.textContent+='\nFAIL '+name+': '+e.message;}}
async function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('documents'))r.result.createObjectStore('documents',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function put(d){const db=await database();await new Promise((r,j)=>{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(d);tx.oncomplete=r;tx.onerror=j;});db.close();}
async function saved(id=docId){const db=await database();const d=await new Promise((r,j)=>{const x=db.transaction('documents').objectStore('documents').get(id);x.onsuccess=()=>r(x.result);x.onerror=j;});db.close();return d;}
const requestBaseline=(await(await fetch('/test-requests')).json()).length;
const bytes=await(await fetch('/cross.pdf')).arrayBuffer(),pdf=await pdfjs.getDocument({data:bytes.slice(0)}).promise,blocks=[];
for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n);blocks.push(...extractPdfParagraphs(await p.getTextContent({includeMarkedContent:true}),p.getViewport({scale:1}),n));}
for(const b of blocks)b.heading=/^(First|Later|Final) section$/.test(b.text.trim());
const left=blocks.filter(b=>b.page===1&&!b.heading&&!b.artifact).at(-1),right=blocks.find(b=>b.page===2&&!b.heading&&!b.artifact);assert(left&&right,'fixture fragments absent');
const docId='v094-auto-'+Date.now(),manualId=docId+'-manual',manualName='手动连接测试-'+Date.now()+'.pdf',base={name:'跨页与目录测试.pdf',type:'pdf',bytes,blocks,pages:2,parser:'docling',doclingLayoutVersion:1,history:[],cards:[],code:[],summary:'',lastPage:1,...await pdfNavigation(pdf,blocks)};
await put({...structuredClone(base),id:manualId,name:manualName});
const complete=left.text+'\n'+right.text;left.text=right.text=complete;left.sourceRef=right.sourceRef='#/texts/cross';left.sourceRefs=right.sourceRefs=['#/texts/cross'];right.continuation=true;
await put({...base,id:docId});localStorage.setItem('paper-space-active-doc',docId);localStorage.setItem('paper-space-seeded','1');localStorage.setItem('paper-space-models',JSON.stringify({profiles:[{id:'isolated-mock',name:'本机模拟模型',baseUrl:'http://127.0.0.1:4382/v1',format:'openai',model:'v094-mock',models:[{id:'v094-mock',name:'本机模拟'}]}],activeId:'isolated-mock'}));
const frame=document.createElement('iframe');frame.src='/';document.getElementById('frame').append(frame);const $=id=>frame.contentDocument?.getElementById(id),q=s=>frame.contentDocument?.querySelector(s),all=s=>[...frame.contentDocument.querySelectorAll(s)];
const click=(selector,text)=>{const b=all(selector).find(b=>b.textContent.includes(text));if(!b)throw Error('Missing '+text);b.click();return b;};const ready=()=>until(()=>$('startupScreen')?.hidden&&q('.pdf-paragraph-notice'),'ready',30000);await ready();
await test('Directory starts at first visible heading, targets later same-page heading and follows scrolling',async()=>{const items=all('.outline-item');assert(items.length===3,'outline missing');items[1].click();await until(()=>q('.outline-item.active')?.textContent.includes('Later section'),'later active');assert($('readerScroll').scrollTop>100,'destination did not scroll');$('readerScroll').dispatchEvent(new frame.contentWindow.WheelEvent('wheel',{deltaY:-100,bubbles:true}));$('readerScroll').scrollTo({top:0,behavior:'instant'});await until(()=>!q('.outline-item.active')?.textContent.includes('Later section'),'top does not select last heading');const nav=$('outline'),active=q('.outline-item.active');if(active)assert(active.getBoundingClientRect().top>=nav.getBoundingClientRect().top&&active.getBoundingClientRect().bottom<=nav.getBoundingClientRect().bottom,'active outline hidden');assert(!q('.outline-page'),'chapter tree still shows page labels');});
await test('Cross-page marker generates one complete request and highlights only current-page native items',async()=>{const marker=q('.paragraph-note[data-block-id="'+left.id+'"]');assert(marker,'first page marker missing');marker.click();await until(()=>q('#annotationDrawer h3')?.textContent==='本机模拟旁注','note generated');const reqs=await(await fetch('/test-requests')).json();assert(reqs.length===requestBaseline+1,'duplicate request');assert(reqs[0].messages.at(-1).content.endsWith(complete),'incomplete input');assert(q('.cross-page-label').textContent.includes('1–2'),'missing range');assert(all('.source-highlight').length===pdfBlockSpans(q('.pdf-page'),left).length,'first page source mismatch');click('#annotationDrawer button','第 2 页原文');await until(()=>q('.pdf-page')?.dataset.page==='2'&&all('.source-highlight').length>0,'second page highlight');assert(all('.source-highlight').length===pdfBlockSpans(q('.pdf-page'),right).length,'second page highlight includes neighbour');const marker2=q('.paragraph-note[data-block-id="'+left.id+'"]');assert(marker2,'continuation marker absent');marker2.click();await until(()=>q('#annotationDrawer h3'));assert((await(await fetch('/test-requests')).json()).length===requestBaseline+1,'continuation made duplicate request');click('#annotationDrawer button','×');});
let quote,noteId;
await test('Native selection creates a local annotation without sending to the model',async()=>{const span=all('.textLayer span').find(s=>s.textContent.includes('Continuation on page two'));assert(span,'native text absent');const r=frame.contentDocument.createRange();r.selectNodeContents(span);frame.contentWindow.getSelection().removeAllRanges();frame.contentWindow.getSelection().addRange(r);span.dispatchEvent(new frame.contentWindow.MouseEvent('mouseup',{bubbles:true,button:0}));assert(!$('selectionMenu').hidden,'selection menu absent');$('annotateSelection').click();assert($('personalNotesDialog').open,'note editor absent');quote=q('.personal-note-quote').textContent;assert(quote.includes('Continuation'),'wrong quote');$('personalNoteText').value='核对跨页段落：这条是我的阅读想法。';click('#personalNotesDialog button','保存批注');await until(async()=>(await saved()).personalNotes?.length===1,'saved note');await until(()=>q('.personal-note-entry'));const d=await saved();noteId=d.personalNotes[0].id;assert(d.personalNotes[0].anchor.page===2&&d.personalNotes[0].anchor.itemIndices.length,'native indices lost');assert((await(await fetch('/test-requests')).json()).length===requestBaseline+1,'personal note sent to model');});
await test('Personal note edit, search, soft-delete and restore preserve source anchor',async()=>{click('.personal-note-entry button','编辑');$('personalNoteText').value='Edited thought <script>unsafe()</script>';click('#personalNotesDialog button','保存批注');await until(()=>q('.personal-note-body')?.textContent.includes('Edited thought'));assert(!q('.personal-note-body script'),'HTML executed');click('.personal-note-entry button','移入已删除');await until(()=>!q('.personal-note-entry'));const toggle=all('.personal-note-filters input')[1];toggle.click();await until(()=>q('.personal-note-entry'));click('.personal-note-entry button','恢复');await until(()=>!q('.personal-note-entry'));all('.personal-note-filters input')[1].click();await until(()=>q('.personal-note-entry'));const search=q('.personal-note-tools input');search.value='not matching';search.dispatchEvent(new frame.contentWindow.Event('input'));assert(!q('.personal-note-entry'),'search ignored');search.value='Edited';search.dispatchEvent(new frame.contentWindow.Event('input'));assert(q('.personal-note-entry'),'search absent');assert((await saved()).personalNotes[0].anchor.text===quote,'anchor changed');$('personalNotesDialog').close();});
await test('Reload restores notes and cross-page card; annotation locates exact saved source',async()=>{frame.contentWindow.location.reload();await sleep(100);await ready();$('personalNotesBtn').click();assert(q('.personal-note-body')?.textContent.includes('Edited'),'note lost on reload');click('.personal-note-entry button','定位原文');await until(()=>all('.source-highlight').length>0,'annotation highlight');const d=await saved();assert(all('.source-highlight').length===d.personalNotes[0].anchor.itemIndices.length,'annotation highlights full cross-page unit instead of selection');assert(d.cards[0].sourceSnapshot.sourceSegments.length===2,'card snapshot lost');});
await test('Manual preview connection persists, uses one shared marker on second page, and undo restores original blocks',async()=>{click('.document-item',manualName);await until(()=>$('docTitle').textContent.includes('手动连接')&&q('.pdf-paragraph-notice'));click('.pdf-paragraph-notice button','跨页段落');assert($('crossPageDialog').open,'cross dialog missing');assert($('crossPageDialog').textContent.includes('第 1 页')&&$('crossPageDialog').textContent.includes('第 2 页'),'preview not explicit');click('#crossPageDialog button','连接这两段');await until(async()=>(await saved(manualId)).crossPageLinks?.length===1);await until(()=>!$('crossPageDialog').open&&q('.paragraph-note[data-block-id^="cross-"]'));const joined=await saved(manualId),unit=readingUnits(joined).find(b=>b.manualLink);assert(unit&&unit.sourceSegments.length===2,'link failed');$('nextPage').click();await until(()=>q('.pdf-page')?.dataset.page==='2'&&q('.paragraph-note[data-block-id="'+unit.id+'"]'));click('.pdf-paragraph-notice button','跨页段落');click('#crossPageDialog button','撤销此连接');await until(async()=>(await saved(manualId)).crossPageLinks[0].deletedAt);assert((await saved(manualId)).blocks.length===base.blocks.length,'original blocks changed');});
await test('Narrow desktop layout contains toolbar, title columns and note dialog without horizontal overflow',async()=>{frame.style.width='1100px';await sleep(700);await until(()=>q('.pdf-paragraph-notice'));assert(frame.contentDocument.documentElement.scrollWidth<=1100,'app overflows');const bar=q('.reader-toolbar');assert(bar.scrollWidth<=bar.clientWidth+1,'toolbar overflows');for(const item of all('.outline-item'))assert(item.scrollWidth<=item.clientWidth+1,'outline text overflows');$('personalNotesBtn').click();assert($('personalNotesDialog').getBoundingClientRect().right<=1100,'note dialog overflows');$('personalNotesDialog').close();frame.style.width='1480px';});
out.textContent+='\n'+passed+' passed, '+failed+' failed';document.title='Tests: '+passed+' passed, '+failed+' failed';
