// Isolated regression fixture: explicitly acknowledge the notice before exercising the app.
import {saveUsageConsent} from '/usage-consent.mjs';saveUsageConsent(localStorage);
import * as pdfjs from '/vendor/pdfjs/build/pdf.mjs';import {extractPdfParagraphs} from '/pdf-layout.mjs';import {pdfNavigation} from '/pdf-navigation.mjs';import {readingUnits} from '/reading-units.mjs';import {pdfBlockSpans} from '/pdf-text.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/build/pdf.worker.mjs';
const out=document.getElementById('results');let passed=0,failed=0;const assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label='condition',timeout=15000){const t=Date.now();while(Date.now()-t<timeout){if(await fn())return;await sleep(40);}throw Error('Timeout '+label);}
async function test(name,fn){try{await fn();passed++;out.textContent+='\nPASS '+name;}catch(e){failed++;out.textContent+='\nFAIL '+name+': '+e.message;}}
async function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('documents'))r.result.createObjectStore('documents',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function put(d){const db=await database();await new Promise((r,j)=>{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(d);tx.oncomplete=r;tx.onerror=j;});db.close();}
async function saved(id=docId){const db=await database();const d=await new Promise((r,j)=>{const x=db.transaction('documents').objectStore('documents').get(id);x.onsuccess=()=>r(x.result);x.onerror=j;});db.close();return d;}

const bytes=await(await fetch('/cross.pdf')).arrayBuffer(),pdf=await pdfjs.getDocument({data:bytes.slice(0)}).promise,blocks=[];
for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n);blocks.push(...extractPdfParagraphs(await p.getTextContent(),p.getViewport({scale:1}),n));}
for(const b of blocks)b.heading=/^(First|Later|Final) section$/.test(b.text.trim());
const docId='v095-'+Date.now(),wordId=docId+'word',sampleId=docId+'sample';
await put({id:docId,name:'导航回归测试.pdf',type:'pdf',bytes,blocks,pages:2,parser:'docling',doclingLayoutVersion:1,history:[],cards:[],code:[],summary:'',lastPage:1,...await pdfNavigation(pdf,blocks)});
const {readWordHTML}=await import('/word-import.mjs');const wp=readWordHTML('<h1>5 Training</h1><p>'+('Opening paragraph for semantic Word reading. '.repeat(28))+'</p><h2>5.1 Training Data and Batching</h2><p>'+('Training data and batches. '.repeat(28))+'</p><h2>5.2 Hardware and Schedule</h2><p>'+('Hardware schedule. '.repeat(28))+'</p><h2>5.3 Optimizer</h2><p>Last section.</p><h1>6 Results</h1><p>Results.</p>');
await put({id:wordId,name:'章节层级与定位.docx',type:'docx',...wp,history:[],cards:[],code:[],summary:'',lastPage:1});
localStorage.setItem('paper-space-active-doc',docId);localStorage.setItem('paper-space-seeded','1');localStorage.removeItem('paper-space-models');
const frame=document.createElement('iframe');frame.src='/';document.getElementById('frame').append(frame);const $=id=>frame.contentDocument?.getElementById(id),q=s=>frame.contentDocument?.querySelector(s),all=s=>[...frame.contentDocument.querySelectorAll(s)];
const chapter=t=>all('.chapter-target').find(b=>b.textContent===t),clickDoc=t=>all('.document-item').find(b=>b.textContent.includes(t)).click();
const ready=()=>until(()=>$('startupScreen')?.hidden&&q('.pdf-paragraph-notice'),'ready',30000);await ready();
await test('Same-page PDF destination keeps original canvas and selected chapter',async()=>{const canvas=q('.pdf-page canvas');chapter('Later section').click();await until(()=>q('.chapter-target.active')?.textContent==='Later section'&&$('readerScroll').scrollTop>100);assert(q('.pdf-page canvas')===canvas,'same page replaced original canvas');assert(!q('.outline-page'),'page labels remain');});
await test('Rapid chapter clicks finish at the last requested PDF heading',async()=>{chapter('Final section').click();chapter('First section').click();chapter('Later section').click();await until(()=>q('.pdf-page')?.dataset.page==='1'&&q('.pdf-paragraph-notice'));await sleep(450);assert(q('.chapter-target.active')?.textContent==='Later section','stale navigation won');assert($('readerScroll').scrollTop>100,'last destination not applied');});
await test('Browsing the chapter list does not move it when reader scroll changes',async()=>{const nav=$('outline');nav.style.height='65px';nav.style.flex='none';nav.dispatchEvent(new frame.contentWindow.PointerEvent('pointerenter'));nav.scrollTop=0;const before=nav.scrollTop;$('readerScroll').dispatchEvent(new frame.contentWindow.WheelEvent('wheel',{deltaY:150,bubbles:true}));$('readerScroll').scrollTop=600;await sleep(100);assert(nav.scrollTop===before,'list moved under pointer');nav.dispatchEvent(new frame.contentWindow.PointerEvent('pointerleave'));nav.style.height='';nav.style.flex='';});
await test('Word chapter tree nests Training subsections without page numbers',async()=>{clickDoc('章节层级与定位');await until(()=>q('.word-page'));chapter('Training').click();await sleep(50);const row=chapter('Training').closest('.chapter-row');assert(row.querySelectorAll('.chapter-children .chapter-target').length===3,'Training hierarchy incorrect');assert(!row.querySelector('.chapter-children').hidden,'selected parent did not open');assert(chapter('Hardware and Schedule'),'child title missing');assert(!all('.chapter-target').some(b=>/^\d/.test(b.textContent)),'chapter numbers still displayed');});
await test('Word same-page jump targets the exact heading, not page top',async()=>{const page=q('.word-page');chapter('Hardware and Schedule').click();await until(()=>q('.chapter-target.active')?.textContent==='Hardware and Schedule');const dest=all('.word-block').find(b=>b.textContent==='5.2 Hardware and Schedule');assert(q('.word-page')===page,'Word page rebuilt');const scroll=$('readerScroll'),actual=dest.getBoundingClientRect().top-scroll.getBoundingClientRect().top;assert(Math.abs(actual-60)<3||(Math.abs(scroll.scrollTop-(scroll.scrollHeight-scroll.clientHeight))<2&&actual>=60&&actual<scroll.clientHeight),'Word did not locate child heading');});
await test('Hover opens a circular picker; wheel previews without changing the document',async()=>{$('chapterWheelBtn').dispatchEvent(new frame.contentWindow.PointerEvent('pointerenter'));await until(()=>!$('chapterWheelPanel').hidden);assert(q('.chapter-dial'),'circular dial absent');const hover=all('.chapter-wheel-choice').find(b=>b.textContent==='Hardware and Schedule');hover.dispatchEvent(new frame.contentWindow.PointerEvent('pointermove',{bubbles:true}));assert(q('.chapter-dial-center strong').textContent==='Hardware and Schedule','mouse preview failed');const before=$('readerScroll').scrollTop,selected=q('.chapter-target.active').textContent;$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.WheelEvent('wheel',{deltaY:100,bubbles:true,cancelable:true}));assert(q('.chapter-dial-center strong').textContent==='Optimizer','wheel did not choose next child');assert($('readerScroll').scrollTop===before&&q('.chapter-target.active').textContent===selected,'wheel changed body before confirmation');q('.chapter-dial-center').click();await until(()=>q('.chapter-target.active')?.textContent==='Optimizer');assert(!$('chapterWheelPanel').hidden,'picker closed on confirm');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));});
await test('Keyboard selects candidate; Escape cancels; direct mouse option commits',async()=>{$('chapterWheelBtn').click();assert(frame.contentDocument.activeElement===$('chapterWheelPanel'),'explicit open has no keyboard focus');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Home',bubbles:true}));assert(q('.chapter-dial-center strong').textContent==='Training','Home failed');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert($('chapterWheelPanel').hidden&&q('.chapter-target.active').textContent==='Optimizer','cancel navigated');$('chapterWheelBtn').click();all('.chapter-wheel-choice').find(b=>b.textContent==='Training Data and Batching').click();await until(()=>q('.chapter-target.active')?.textContent==='Training Data and Batching');assert(!$('chapterWheelPanel').hidden,'direct option closed picker');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));});
await test('Narrow layout keeps the wheel and full chapter choices within the viewport',async()=>{frame.style.width='1000px';await sleep(500);$('chapterWheelBtn').click();const r=$('chapterWheelPanel').getBoundingClientRect();assert(r.left>=0&&r.right<=1000&&r.top>=0&&r.bottom<=1000,'wheel outside viewport');assert(frame.contentDocument.documentElement.scrollWidth<=1000,'page overflows');for(const b of all('.chapter-target'))assert(b.scrollWidth<=b.clientWidth+1,'chapter text overflows');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));frame.style.width='1480px';await sleep(400);});
await test('Public Transformer paper exposes Training children and jumps to Hardware',async()=>{const sampleBytes=await(await fetch('/demo.pdf')).arrayBuffer(),samplePdf=await pdfjs.getDocument({data:sampleBytes.slice(0)}).promise,sampleBlocks=[];for(let n=1;n<=samplePdf.numPages;n++){const p=await samplePdf.getPage(n);sampleBlocks.push(...extractPdfParagraphs(await p.getTextContent(),p.getViewport({scale:1}),n));}const nav=await pdfNavigation(samplePdf,sampleBlocks);await put({id:sampleId,name:'Attention Is All You Need',type:'pdf',bytes:sampleBytes,blocks:sampleBlocks,pages:samplePdf.numPages,parser:'docling',doclingLayoutVersion:1,history:[],cards:[],code:[],summary:'',lastPage:7,...nav});localStorage.setItem('paper-space-active-doc',sampleId);frame.contentWindow.location.reload();await sleep(100);await ready();assert(chapter('Training'),'Training missing');chapter('Training').click();await sleep(100);const row=chapter('Training').closest('.chapter-row');assert(row.querySelectorAll('.chapter-children .chapter-target').length>=4,'actual paper lost child hierarchy');chapter('Hardware and Schedule').click();await until(()=>q('.chapter-target.active')?.textContent==='Hardware and Schedule');assert($('pageInput').value==='7','wrong physical page');assert($('readerScroll').scrollTop>300,'same-page destination missing');});
await test('Expanded parent remains visible while scrolling its child chapters',async()=>{const nav=$('outline'),row=chapter('Training').closest('.chapter-row');nav.style.height='150px';nav.style.flex='none';nav.dispatchEvent(new frame.contentWindow.PointerEvent('pointerenter'));nav.scrollTop+=row.getBoundingClientRect().top-nav.getBoundingClientRect().top+30;await sleep(40);const heading=row.querySelector('.chapter-row-heading');assert(Math.abs(heading.getBoundingClientRect().top-nav.getBoundingClientRect().top)<2,'main chapter scrolled out of view');nav.style.height='';nav.style.flex='';nav.dispatchEvent(new frame.contentWindow.PointerEvent('pointerleave'));});
out.textContent+='\n'+passed+' passed, '+failed+' failed';document.title='Tests: '+passed+' passed, '+failed+' failed';
