import test from 'node:test';import assert from 'node:assert/strict';import {chaptersFor} from '../public/chapter-navigation.mjs';import {chapterIdentity,chapterNoteAnchor,notesForChapter,chapterForAnchor,resolveChapter,anchorWithChapter} from '../public/chapter-notes.mjs';import {savePersonalNote,setNoteDeleted,exportPersonalNotes} from '../public/personal-notes.mjs';
const fixture=()=>({pages:3,outline:[{title:'3 Model Architecture',page:1,depth:0,y:20},{title:'3.2 Attention',page:1,depth:1,y:150},{title:'3.2.1 Scaled Dot-Product Attention',page:1,depth:2,y:300},{title:'3.2.2 Multi-Head Attention',page:2,depth:2,y:180}],blocks:[{id:'selection-source',page:1,y:360,text:'native text',itemIndices:[7,8]}]});
test('Chapter note stores an immutable full hierarchy and remains in exactly one section',()=>{const d=fixture(),c=chaptersFor(d),a=chapterNoteAnchor(d,c[2]);const note=savePersonalNote(d,{text:'my thought',anchor:a});a.chapter.title='changed';assert.equal(note.anchor.chapter.title,c[2].title);assert.deepEqual(note.anchor.chapter.path,['Model Architecture','Attention','Scaled Dot-Product Attention']);assert.equal(notesForChapter(d,c[2]).length,1);assert.equal(notesForChapter(d,c[1]).length,0);assert.equal(notesForChapter(d,c[3]).length,0);assert.match(exportPersonalNotes(d),/Scaled Dot-Product Attention/);});
test('Note binding survives a new earlier outline item without depending on array index',()=>{const d=fixture(),c=chaptersFor(d)[2],a=chapterNoteAnchor(d,c);savePersonalNote(d,{text:'stable',anchor:a});d.outline.unshift({title:'Abstract',page:1,depth:0,y:0});const shifted=chaptersFor(d)[3];assert.equal(chapterIdentity(c),chapterIdentity(shifted));assert.equal(notesForChapter(d,shifted).length,1);assert.equal(resolveChapter(d,a.chapter).title,c.title);});
test('Same-page selection is linked by source position while ambiguous page-only history stays unassigned',()=>{const d=fixture(),c=chaptersFor(d);assert.equal(chapterForAnchor(d,{page:1,blockId:'selection-source'}).key,c[2].key);assert.equal(chapterForAnchor(d,{page:1,itemIndices:[7]}).key,c[2].key);assert.equal(chapterForAnchor(d,{page:1}),null);const a=anchorWithChapter(d,{page:1,blockId:'selection-source',text:'native text',itemIndices:[7,8]});assert.deepEqual(a.itemIndices,[7,8]);assert.equal(a.chapter.title,c[2].title);});
test('Deleted notes retain chapter association across JSON reload and restore',()=>{let d=fixture();const c=chaptersFor(d)[2],n=savePersonalNote(d,{text:'memo',anchor:chapterNoteAnchor(d,c)});setNoteDeleted(d,n.id,true);d=JSON.parse(JSON.stringify(d));assert.equal(notesForChapter(d,c).length,0);assert.equal(notesForChapter(d,c,{deleted:true}).length,1);setNoteDeleted(d,n.id,false);assert.equal(notesForChapter(d,c).length,1);});
test('Changed chapter targets are not silently rebound to a neighbouring section',()=>{const d=fixture(),c=chaptersFor(d)[2],a=chapterNoteAnchor(d,c);savePersonalNote(d,{text:'memo',anchor:a});d.outline.splice(2,1);assert.equal(resolveChapter(d,a.chapter),null);assert.equal(chapterForAnchor(d,a),null);assert.equal(d.personalNotes.length,1);assert.equal(notesForChapter(d,chaptersFor(d)[1]).length,0);});

test('Word selection associates with its actual same-page heading by stable block order',()=>{const d={type:'docx',pages:1,blocks:[{id:'h1',page:1,text:'Training',heading:true,headingLevel:1},{id:'h2',page:1,text:'Hardware',heading:true,headingLevel:2},{id:'body',page:1,text:'original sentence'},{id:'h3',page:1,text:'Optimizer',heading:true,headingLevel:2}]};const a=anchorWithChapter(d,{page:1,blockId:'body',text:'sentence'});assert.equal(a.chapter.title,'Hardware');assert.equal(a.blockId,'body');assert.equal(a.text,'sentence');});
