// Isolated regression fixture: explicitly acknowledge the notice before exercising the app.
import {saveUsageConsent} from '/usage-consent.mjs';saveUsageConsent(localStorage);
import * as pdfjs from '/vendor/pdfjs/build/pdf.mjs';import {extractPdfParagraphs} from '/pdf-layout.mjs';import {pdfNavigation} from '/pdf-navigation.mjs';import {readingUnits} from '/reading-units.mjs';import {pdfBlockSpans} from '/pdf-text.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/build/pdf.worker.mjs';
const out=document.getElementById('results');let passed=0,failed=0;const assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label='condition',timeout=15000){const t=Date.now();while(Date.now()-t<timeout){if(await fn())return;await sleep(40);}throw Error('Timeout '+label);}
async function test(name,fn){try{await fn();passed++;out.textContent+='\nPASS '+name;}catch(e){failed++;out.textContent+='\nFAIL '+name+': '+e.message;}}
async function database(){return new Promise((resolve,reject)=>{const r=indexedDB.open('paper-space',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('documents'))r.result.createObjectStore('documents',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function put(d){const db=await database();await new Promise((r,j)=>{const tx=db.transaction('documents','readwrite');tx.objectStore('documents').put(d);tx.oncomplete=r;tx.onerror=j;});db.close();}
async function saved(id=docId){const db=await database();const d=await new Promise((r,j)=>{const x=db.transaction('documents').objectStore('documents').get(id);x.onsuccess=()=>r(x.result);x.onerror=j;});db.close();return d;}

const bytes=await(await fetch('/cross.pdf')).arrayBuffer(),pdf=await pdfjs.getDocument({data:bytes.slice(0)}).promise,blocks=[];
for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n);blocks.push(...extractPdfParagraphs(await p.getTextContent(),p.getViewport({scale:1}),n));}
for(const b of blocks)b.heading=/^(First|Later|Final) section$/.test(b.text.trim());
const docId='v096-'+Date.now(),wordId=docId+'word',sampleId=docId+'sample';
await put({id:docId,name:'导航回归测试.pdf',type:'pdf',bytes,blocks,pages:2,parser:'docling',doclingLayoutVersion:1,history:[],cards:[],code:[],summary:'',lastPage:1,...await pdfNavigation(pdf,blocks)});
const {readWordHTML}=await import('/word-import.mjs');const wp=readWordHTML('<h1>5 Training</h1><p>'+('Opening paragraph for semantic Word reading. '.repeat(28))+'</p><h2>5.1 Training Data and Batching</h2><p>'+('Training data and batches. '.repeat(28))+'</p><h2>5.2 Hardware and Schedule</h2><p>'+('Hardware schedule. '.repeat(28))+'</p><h2>5.3 Optimizer</h2><p>Last section.</p><h1>6 Results</h1><p>Results.</p>');
await put({id:wordId,name:'章节层级与定位-'+wordId+'.docx',type:'docx',...wp,history:[],cards:[],code:[],summary:'',lastPage:1});
localStorage.setItem('paper-space-active-doc',docId);localStorage.setItem('paper-space-seeded','1');localStorage.removeItem('paper-space-models');
const frame=document.createElement('iframe');frame.src='/';document.getElementById('frame').append(frame);const $=id=>frame.contentDocument?.getElementById(id),q=s=>frame.contentDocument?.querySelector(s),all=s=>[...frame.contentDocument.querySelectorAll(s)];
const chapter=t=>all('.chapter-target').find(b=>b.textContent===t),clickDoc=t=>all('.document-item').find(b=>b.textContent.includes(t)).click();
const ready=()=>until(()=>$('startupScreen')?.hidden&&q('.pdf-paragraph-notice'),'ready',30000);await ready();
await test('Same-page PDF destination keeps original canvas and selected chapter',async()=>{const canvas=q('.pdf-page canvas');chapter('Later section').click();await until(()=>q('.chapter-target.active')?.textContent==='Later section'&&$('readerScroll').scrollTop>100);assert(q('.pdf-page canvas')===canvas,'same page replaced original canvas');assert(!q('.outline-page'),'page labels remain');});
await test('Rapid chapter clicks finish at the last requested PDF heading',async()=>{chapter('Final section').click();chapter('First section').click();chapter('Later section').click();await until(()=>q('.pdf-page')?.dataset.page==='1'&&q('.pdf-paragraph-notice'));await sleep(450);assert(q('.chapter-target.active')?.textContent==='Later section','stale navigation won');assert($('readerScroll').scrollTop>100,'last destination not applied');});
await test('Browsing the chapter list does not move it when reader scroll changes',async()=>{const nav=$('outline');nav.style.height='65px';nav.style.flex='none';nav.dispatchEvent(new frame.contentWindow.PointerEvent('pointerenter'));nav.scrollTop=0;const before=nav.scrollTop;$('readerScroll').dispatchEvent(new frame.contentWindow.WheelEvent('wheel',{deltaY:150,bubbles:true}));$('readerScroll').scrollTop=600;await sleep(100);assert(nav.scrollTop===before,'list moved under pointer');nav.dispatchEvent(new frame.contentWindow.PointerEvent('pointerleave'));nav.style.height='';nav.style.flex='';});
await test('Word chapter tree nests Training subsections without page numbers',async()=>{clickDoc('章节层级与定位-'+wordId);await until(()=>q('.word-page'));chapter('Training').click();await sleep(50);const row=chapter('Training').closest('.chapter-row');assert(row.querySelectorAll('.chapter-children .chapter-target').length===3,'Training hierarchy incorrect');assert(!row.querySelector('.chapter-children').hidden,'selected parent did not open');assert(chapter('Hardware and Schedule'),'child title missing');assert(!all('.chapter-target').some(b=>/^\d/.test(b.textContent)),'chapter numbers still displayed');});
await test('Word same-page jump targets the exact heading, not page top',async()=>{const page=q('.word-page');chapter('Hardware and Schedule').click();await until(()=>q('.chapter-target.active')?.textContent==='Hardware and Schedule');const dest=all('.word-block').find(b=>b.textContent==='5.2 Hardware and Schedule');assert(q('.word-page')===page,'Word page rebuilt');const scroll=$('readerScroll'),actual=dest.getBoundingClientRect().top-scroll.getBoundingClientRect().top;assert(Math.abs(actual-60)<3||(Math.abs(scroll.scrollTop-(scroll.scrollHeight-scroll.clientHeight))<2&&actual>=60&&actual<scroll.clientHeight),'Word did not locate child heading');});
await test('Hover opens a circular picker; wheel previews without changing the document',async()=>{$('chapterWheelBtn').dispatchEvent(new frame.contentWindow.PointerEvent('pointerenter'));await until(()=>!$('chapterWheelPanel').hidden);assert(q('.chapter-dial'),'circular dial absent');const hover=all('.chapter-wheel-choice').find(b=>b.textContent==='Hardware and Schedule');hover.dispatchEvent(new frame.contentWindow.PointerEvent('pointermove',{bubbles:true}));assert(q('.chapter-dial-center strong').textContent==='Hardware and Schedule','mouse preview failed');const before=$('readerScroll').scrollTop,selected=q('.chapter-target.active').textContent;$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.WheelEvent('wheel',{deltaY:100,bubbles:true,cancelable:true}));assert(q('.chapter-dial-center strong').textContent==='Optimizer','wheel did not choose next child');assert($('readerScroll').scrollTop===before&&q('.chapter-target.active').textContent===selected,'wheel changed body before confirmation');q('.chapter-dial-center').click();await until(()=>q('.chapter-target.active')?.textContent==='Optimizer');assert(!$('chapterWheelPanel').hidden,'picker closed on confirm');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));});
await test('Keyboard selects candidate; Escape cancels; direct mouse option commits',async()=>{$('chapterWheelBtn').click();assert(frame.contentDocument.activeElement===$('chapterWheelPanel'),'explicit open has no keyboard focus');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Home',bubbles:true}));assert(q('.chapter-dial-center strong').textContent==='Training','Home failed');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert($('chapterWheelPanel').hidden&&q('.chapter-target.active').textContent==='Optimizer','cancel navigated');$('chapterWheelBtn').click();all('.chapter-wheel-choice').find(b=>b.textContent==='Training Data and Batching').click();await until(()=>q('.chapter-target.active')?.textContent==='Training Data and Batching');assert(!$('chapterWheelPanel').hidden,'direct option closed picker');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));});
await test('Narrow layout keeps the wheel and full chapter choices within the viewport',async()=>{frame.style.width='1000px';await sleep(500);$('chapterWheelBtn').click();const r=$('chapterWheelPanel').getBoundingClientRect();assert(r.left>=0&&r.right<=1000&&r.top>=0&&r.bottom<=1000,'wheel outside viewport');assert(frame.contentDocument.documentElement.scrollWidth<=1000,'page overflows');for(const b of all('.chapter-target'))assert(b.scrollWidth<=b.clientWidth+1,'chapter text overflows');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));frame.style.width='1480px';await sleep(400);});
await test('Public Transformer paper exposes Training children and jumps to Hardware',async()=>{const sampleBytes=await(await fetch('/demo.pdf')).arrayBuffer(),samplePdf=await pdfjs.getDocument({data:sampleBytes.slice(0)}).promise,sampleBlocks=[];for(let n=1;n<=samplePdf.numPages;n++){const p=await samplePdf.getPage(n);sampleBlocks.push(...extractPdfParagraphs(await p.getTextContent(),p.getViewport({scale:1}),n));}const nav=await pdfNavigation(samplePdf,sampleBlocks);await put({id:sampleId,name:'Attention Is All You Need',type:'pdf',bytes:sampleBytes,blocks:sampleBlocks,pages:samplePdf.numPages,parser:'docling',doclingLayoutVersion:1,history:[],cards:[],code:[],summary:'',lastPage:7,...nav});localStorage.setItem('paper-space-active-doc',sampleId);frame.contentWindow.location.reload();await sleep(100);await ready();assert(chapter('Training'),'Training missing');chapter('Training').click();await sleep(100);const row=chapter('Training').closest('.chapter-row');assert(row.querySelectorAll('.chapter-children .chapter-target').length>=4,'actual paper lost child hierarchy');chapter('Hardware and Schedule').click();await until(()=>q('.chapter-target.active')?.textContent==='Hardware and Schedule');assert($('pageInput').value==='7','wrong physical page');assert($('readerScroll').scrollTop>300,'same-page destination missing');});
await test('Expanded parent remains visible while scrolling its child chapters',async()=>{const nav=$('outline'),row=chapter('Training').closest('.chapter-row');nav.style.height='150px';nav.style.flex='none';nav.dispatchEvent(new frame.contentWindow.PointerEvent('pointerenter'));nav.scrollTop+=row.getBoundingClientRect().top-nav.getBoundingClientRect().top+30;await sleep(40);const heading=row.querySelector('.chapter-row-heading');assert(Math.abs(heading.getBoundingClientRect().top-nav.getBoundingClientRect().top)<2,'main chapter scrolled out of view');nav.style.height='';nav.style.flex='';nav.dispatchEvent(new frame.contentWindow.PointerEvent('pointerleave'));});

const noteButton=title=>chapter(title).parentElement.querySelector('.chapter-note-button');const pressButton=(selector,text)=>{const b=all(selector).find(x=>x.textContent.includes(text));assert(b,'button absent: '+text);b.click();};
await test('Picker stays open after pointer leaves and closes only on explicit dismissal',async()=>{$('chapterWheelBtn').dispatchEvent(new frame.contentWindow.PointerEvent('pointerenter'));await until(()=>!$('chapterWheelPanel').hidden);$('chapterWheelBtn').dispatchEvent(new frame.contentWindow.PointerEvent('pointerleave'));$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.PointerEvent('pointerleave'));await sleep(500);assert(!$('chapterWheelPanel').hidden,'hover leave closed picker');$('docTitle').dispatchEvent(new frame.contentWindow.PointerEvent('pointerdown',{bubbles:true}));assert($('chapterWheelPanel').hidden,'outside click did not close');});
await test('Real nested PDF headings show levels, indentation and owning path, while repeated navigation keeps wheel open',async()=>{chapter('Model Architecture').click();await until(()=>q('.chapter-target.active')?.textContent==='Model Architecture');$('chapterWheelBtn').click();const attention=all('.chapter-wheel-choice').find(b=>b.textContent==='Attention'),scaled=all('.chapter-wheel-choice').find(b=>b.textContent==='Scaled Dot-Product Attention');assert(attention&&scaled,'nested entries absent');assert(attention.parentElement.dataset.depth==='1'&&scaled.parentElement.dataset.depth==='2','heading levels flattened');assert(scaled.parentElement.style.getPropertyValue('--chapter-indent')!==attention.parentElement.style.getPropertyValue('--chapter-indent'),'nested indentation absent');scaled.click();await until(()=>$('pageInput').value==='4'&&q('.chapter-target.active')?.textContent==='Scaled Dot-Product Attention');assert(!$('chapterWheelPanel').hidden,'first click closed wheel');assert(q('.chapter-wheel-path').textContent.includes('Model Architecture › Attention › Scaled Dot-Product Attention'),'owning path absent');all('.chapter-wheel-choice').find(b=>b.textContent==='Multi-Head Attention').click();await until(()=>q('.chapter-target.active')?.textContent==='Multi-Head Attention');assert(!$('chapterWheelPanel').hidden,'second click closed wheel');assert(q('.chapter-wheel-choice[aria-current=location]').textContent==='Multi-Head Attention','reading marker stale');$('chapterWheelPanel').dispatchEvent(new frame.contentWindow.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));});
let chapterNoteId;
await test('Left-of-chapter note creates a section-bound annotation even when reading a different page',async()=>{const b=noteButton('Hardware and Schedule');assert(b.compareDocumentPosition(chapter('Hardware and Schedule'))&4,'note is not left of chapter');b.click();assert($('personalNotesDialog').open&&q('.personal-note-scope').textContent.includes('Hardware and Schedule'),'wrong section dialog');pressButton('#personalNotesDialog button','为本节写批注');$('personalNoteText').value='Check the hardware schedule against training duration.';pressButton('#personalNotesDialog button','保存批注');await until(()=>q('.personal-note-entry'));const d=await saved(sampleId),note=d.personalNotes.at(-1);chapterNoteId=note.id;assert(note.anchor.page===7&&note.anchor.chapter.title==='Hardware and Schedule','annotation follows current page instead of its chapter');assert(noteButton('Hardware and Schedule').textContent==='1','sidebar count not updated');assert(noteButton('Optimizer').textContent==='✎','note leaked into neighbouring chapter');$('personalNotesDialog').close();});
await test('Chapter scope isolates sibling notes and exact source navigation targets its heading',async()=>{noteButton('Optimizer').click();assert(!q('.personal-note-entry'),'sibling note appears in section');$('personalNotesDialog').close();noteButton('Hardware and Schedule').click();pressButton('#personalNotesDialog button','定位原文');await until(()=>q('.pdf-page')?.dataset.page==='7'&&q('.pdf-paragraph-notice')&&q('.chapter-target.active')?.textContent==='Hardware and Schedule'&&$('readerScroll').scrollTop>300,'chapter heading reached');});
await test('Chapter note editing, soft delete and restore update only its own badge',async()=>{noteButton('Hardware and Schedule').click();pressButton('.personal-note-entry button','编辑');$('personalNoteText').value='Revised section thought.';pressButton('#personalNotesDialog button','保存批注');await until(()=>q('.personal-note-body')?.textContent==='Revised section thought.');pressButton('.personal-note-entry button','移入已删除');await until(()=>!q('.personal-note-entry'));assert(noteButton('Hardware and Schedule').textContent==='✎','deleted note counted');q('.personal-note-filters input').click();await until(()=>q('.personal-note-entry'));pressButton('.personal-note-entry button','恢复');await until(()=>noteButton('Hardware and Schedule').textContent==='1');$('personalNotesDialog').close();});
await test('Reload preserves chapter scope and export keeps its heading while original notes remain available globally',async()=>{frame.contentWindow.location.reload();await sleep(100);await ready();assert(noteButton('Hardware and Schedule').textContent==='1','chapter count lost after reload');noteButton('Hardware and Schedule').click();assert(q('.personal-note-body')?.textContent==='Revised section thought.','section note lost');pressButton('#personalNotesDialog button','查看全部批注');assert(!q('.personal-note-scope')&&q('.personal-note-body'),'all-notes view unavailable');const {exportPersonalNotes}=await import('/personal-notes.mjs');assert(exportPersonalNotes(await saved(sampleId)).includes('Hardware and Schedule'),'export lost chapter association');$('personalNotesDialog').close();});
await test('Chapter annotation remains private and no real or mock model was called',async()=>{assert((await(await fetch('/test-requests')).json()).length===0,'annotation called model');const {buildMaterials}=await import('/context.mjs');const d=await saved(sampleId);const materials=buildMaterials(d,7,null,'training',[],new Set());assert(!JSON.stringify(materials).includes('Revised section thought.'),'private note entered model context');});
await test('Word chapter note locates its original heading without rebuilding the reading page',async()=>{clickDoc('章节层级与定位-'+wordId);await until(()=>q('.word-page'));chapter('Training').click();noteButton('Hardware and Schedule').click();pressButton('#personalNotesDialog button','为本节写批注');$('personalNoteText').value='Word section note.';pressButton('#personalNotesDialog button','保存批注');await until(()=>q('.personal-note-entry'));const d=await saved(wordId);assert(d.personalNotes[0].anchor.chapter.blockId,'Word target block missing');const page=q('.word-page');pressButton('#personalNotesDialog button','定位原文');await until(()=>q('.chapter-target.active')?.textContent==='Hardware and Schedule');assert(q('.word-page')===page,'Word page rebuilt');assert(q('.chapter-destination')?.textContent==='5.2 Hardware and Schedule','wrong Word source');});
out.textContent+='\n'+passed+' passed, '+failed+' failed';document.title='Tests: '+passed+' passed, '+failed+' failed';
